### ISSUE TITLE
"Could not find entry in `obsm` for 'umap'.\nAvailable keys are: ['X_pca']."

### ISSUE THREAD

**Issue by jesusdpa1** [scverse/scanpy#1095]
Hi,

I am trying to run the Preprocessing and clustering example pipeline in our 10x dataset and when I reach to the point of plotting the UMAP -> sc.pl.umap(adata) I started observing the following error

Traceback (most recent call last):
  File "/home/jesuspenaloza/anaconda3/envs/pyrna/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-32-ccd41cdd9550>", line 3, in <module>
    sc.pl.umap(adata)
  File "/home/jesuspenaloza/anaconda3/envs/pyrna/lib/python3.6/site-packages/scanpy/plotting/_tools/scatterplots.py", line 524, in umap
    return embedding(adata, 'umap', **kwargs)
  File "/home/jesuspenaloza/anaconda3/envs/pyrna/lib/python3.6/site-packages/scanpy/plotting/_tools/scatterplots.py", line 133, in embedding
    data_points, components_list = _get_data_points(adata, basis, projection, components)
  File "/home/jesuspenaloza/anaconda3/envs/pyrna/lib/python3.6/site-packages/scanpy/plotting/_tools/scatterplots.py", line 646, in _get_data_points
    f"Could not find entry in `obsm` for '{basis}'.\n"
KeyError: "Could not find entry in `obsm` for 'umap'.\nAvailable keys are: ['X_pca']."

our data structure is the following 

adata
Out[34]: 
AnnData object with n_obs × n_vars = 1858 × 366 
    obs: 'n_genes', 'percent_mito', 'n_counts', 'leiden'
    var: 'gene_ids', 'feature_types', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'log1p', 'pca', 'neighbors', 'leiden'
    obsm: 'X_pca'
    varm: 'PCs'

![image](https://user-images.githubusercontent.com/17010046/76561178-23a41e00-6479-11ea-85d5-ec6982f0bd59.png)

**Comment by LuckyMD** [comment]
Hi! You need to first compute the umap layout using `sc.tl.umap(adata)` it looks like you may have missed that here.

**Comment by jesusdpa1** [comment]
Thank you!
