### ISSUE TITLE
Combat processing errors/warnings in console

### ISSUE THREAD

**Issue by auesro** [scverse/scanpy#1164]
Console outputs a long list of errors/warnings when running scanpy.pp.combat().
  

```
adataCombat = sc.read_h5ad(results_file)
sc.pp.highly_variable_genes(adataCombat)
sc.pp.pca(adataCombat, svd_solver='arpack')
sc.pp.combat(adataCombat, key='sample')
```

```
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py:269: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "_it_sol" failed type inference due to: Cannot unify array(float64, 2d, C) and array(float64, 1d, C) for 'sum2', defined at /home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py (311)

File "../../../anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 311:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
        g_new = (t2*n*g_hat + d_old*g_bar) / (t2*n + d_old)
        sum2 = s_data - g_new.reshape((g_new.shape[0], 1)) @ np.ones((1, s_data.shape[1]))
        ^

[1] During: typing of assignment at /home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py (313)

File "../../../anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 313:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
        sum2 = sum2 ** 2
        sum2 = sum2.sum(axis=1)
        ^

  @numba.jit
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py:269: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "_it_sol" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "../../../anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 305:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
    change = 1
    count = 0
    ^

  @numba.jit
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/numba/compiler.py:742: NumbaWarning: Function "_it_sol" was compiled in object mode without forceobj=True, but has lifted loops.

File "../../../anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 270:
@numba.jit
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
^

  self.func_ir.loc))
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py:269: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "_it_sol" failed type inference due to: Cannot unify array(float64, 2d, C) and array(float64, 1d, C) for 'sum2', defined at /home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py (311)

File "../../../anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 311:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
        g_new = (t2*n*g_hat + d_old*g_bar) / (t2*n + d_old)
        sum2 = s_data - g_new.reshape((g_new.shape[0], 1)) @ np.ones((1, s_data.shape[1]))
        ^

[1] During: typing of assignment at /home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py (313)

File "../../../anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 313:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
        sum2 = sum2 ** 2
        sum2 = sum2.sum(axis=1)
        ^

  @numba.jit
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/numba/compiler.py:742: NumbaWarning: Function "_it_sol" was compiled in object mode without forceobj=True.

File "../../../anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 305:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
    change = 1
    count = 0
    ^

  self.func_ir.loc))
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py:235: RuntimeWarning: divide by zero encountered in true_divide
  b_prior[i],
```

#### Versions:

> scanpy==1.4.4.post1 anndata==0.6.22.post1 umap==0.3.10 numpy==1.18.1 scipy==1.4.1 pandas==1.0.3 scikit-learn==0.22.2.post1 statsmodels==0.11.1 python-igraph==0.7.1 louvain==0.6.1

**Comment by ivirshup** [comment]
Could you report your numba version, and also try updating your version of anndata? I'm not able to reproduce this on my end with either dense or sparse arrays in "X".

If issues still occur, can you make an reduced example that replicates the bug which I could run on my machine?

**Comment by auesro** [comment]
Hi @ivirshup ,
Thanks for your help.
Versions:
```
In [1]: import numba
In [2]: numba.__version__
Out[2]: '0.45.0'
```
I had to downgrade the original numba version in order to MNN_correct to work according to a Stackoverflow post.
Now I updated anndata through conda:
```conda update anndata```
And ran this code (minus highly variable gene calculation):
```
adataCombat = sc.read_h5ad(results_file)
#Run combat:
# sc.pp.highly_variable_genes(adataCombat)
sc.pp.pca(adataCombat, svd_solver='arpack')
sc.pp.combat(adataCombat, key='sample')
sc.pp.neighbors(adataCombat, n_pcs =50)
```
with even worse output:
```
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py:269: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "_it_sol" failed type inference due to: Cannot unify array(float64, 2d, C) and array(float64, 1d, C) for 'sum2', defined at /home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py (311)

File "anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 311:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
        g_new = (t2*n*g_hat + d_old*g_bar) / (t2*n + d_old)
        sum2 = s_data - g_new.reshape((g_new.shape[0], 1)) @ np.ones((1, s_data.shape[1]))
        ^

[1] During: typing of assignment at /home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py (313)

File "anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 313:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
        sum2 = sum2 ** 2
        sum2 = sum2.sum(axis=1)
        ^

  @numba.jit
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py:269: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "_it_sol" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 305:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
    change = 1
    count = 0
    ^

  @numba.jit
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/numba/compiler.py:742: NumbaWarning: Function "_it_sol" was compiled in object mode without forceobj=True, but has lifted loops.

File "anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 270:
@numba.jit
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
^

  self.func_ir.loc))
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py:269: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "_it_sol" failed type inference due to: Cannot unify array(float64, 2d, C) and array(float64, 1d, C) for 'sum2', defined at /home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py (311)

File "anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 311:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
        g_new = (t2*n*g_hat + d_old*g_bar) / (t2*n + d_old)
        sum2 = s_data - g_new.reshape((g_new.shape[0], 1)) @ np.ones((1, s_data.shape[1]))
        ^

[1] During: typing of assignment at /home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py (313)

File "anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 313:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
        sum2 = sum2 ** 2
        sum2 = sum2.sum(axis=1)
        ^

  @numba.jit
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/numba/compiler.py:742: NumbaWarning: Function "_it_sol" was compiled in object mode without forceobj=True.

File "anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py", line 305:
def _it_sol(s_data, g_hat, d_hat, g_bar, t2, a, b, conv=0.0001) -> Tuple[float, float]:
    <source elided>
    change = 1
    count = 0
    ^

  self.func_ir.loc))
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_combat.py:235: RuntimeWarning: divide by zero encountered in true_divide
  b_prior[i],
Traceback (most recent call last):

  File "<ipython-input-2-523dfec14840>", line 6, in <module>
    sc.pp.neighbors(adataCombat, n_pcs =50)

  File "/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/neighbors/__init__.py", line 95, in neighbors
    random_state=random_state,

  File "/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/neighbors/__init__.py", line 683, in compute_neighbors
    self.n_neighbors,

  File "/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/neighbors/__init__.py", line 324, in compute_connectivities_umap
    return distances, connectivities.tocsr()

AttributeError: 'tuple' object has no attribute 'tocsr'
```
Now ```sc.pp.neighbors()``` cannot run on the data...

**Comment by ivirshup** [comment]
Ah, looks like that might be it. I think your scanpy and numba installs might be old versions. Could you upgrade those and let me know if that works?

**Comment by auesro** [comment]
I recreated the whole environment from scratch and now all issues are gone with Combat.
Thanks a lot!
