### ISSUE TITLE
regress_out() error

### ISSUE THREAD

**Issue by auesro** [scverse/scanpy#1171]
Running ```sc.pp.regress_out(adata, ['n_counts'])``` or in any other obs, it outputs error on the "first guess". I have used the function before with no problems. So I am not sure where the issue is now (I have updated to the latest version of Scanpy 2 days ago...but I dont know if it has anything to do with it). I have followed the steps in this [tutorial](https://github.com/theislab/scanpy-tutorials/blob/master/pbmc3k.ipynb).
I must add that this ```adata``` object is a subset of all cells created by keeping only the cells that express the gene Crabp1, as follows:
```adata = adata_full[adata_full.obs['Crabp1_cell'] == 'True']```

```
sc.pp.regress_out(adata, ['n_counts'])
```

```
sc.pp.regress_out(adata, ['n_counts'])
regressing out ['n_counts']
/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/statsmodels/genmod/families/family.py:179: RuntimeWarning: invalid value encountered in true_divide
  return np.sum(resid_dev * freq_weights * var_weights / scale)
Traceback (most recent call last):

  File "<ipython-input-6-4693dee26417>", line 1, in <module>
    sc.pp.regress_out(adata, ['n_counts'])

  File "/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_simple.py", line 841, in regress_out
    res = list(map(_regress_out_chunk, tasks))

  File "/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_simple.py", line 867, in _regress_out_chunk
    result = sm.GLM(data_chunk[:, col_index], regres, family=sm.families.Gaussian()).fit()

  File "/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1027, in fit
    cov_kwds=cov_kwds, use_t=use_t, **kwargs)

  File "/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1142, in _fit_irls
    raise ValueError("The first guess on the deviance function "

ValueError: The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.
```

#### Versions:

> scanpy==1.4.6 anndata==0.7.1 umap==0.4.1 numpy==1.18.1 scipy==1.4.1 pandas==1.0.3 scikit-learn==0.22.2.post1 statsmodels==0.11.1 python-igraph==0.8.0

**Comment by auesro** [comment]
Alright, solved following advice given here: #230
