### ISSUE TITLE
shape mismatch with bbknn

### ISSUE THREAD

**Issue by dweemx** [scverse/scanpy#1222]
I'm trying to run BBKNN on a AnnData object built with `scanpy==1.4.6` but it's failing when getting the graph.

```python
sc.external.pp.bbknn(
    adata,
    batch_key="batch",
    n_pcs=21,
    neighbors_within_batch=5,
    trim=0)
```

```pytb
Command error:
  Traceback (most recent call last):
    File "~/sc_batch_effect_correction.py", line 160, in <module>
      trim=args.trim)
    File "/opt/venv/lib/python3.7/site-packages/scanpy/external/pp/_bbknn.py", line 120, in bbknn
      **kwargs,
    File "/opt/venv/lib/python3.7/site-packages/bbknn/__init__.py", line 281, in bbknn
      approx=approx, metric=metric, **kwargs)
    File "/opt/venv/lib/python3.7/site-packages/bbknn/__init__.py", line 325, in bbknn_pca_matrix
      neighbors_within_batch=neighbors_within_batch)
    File "/opt/venv/lib/python3.7/site-packages/bbknn/__init__.py", line 168, in get_graph
      knn_indices[ind_from[:,None],col_range[None,:]] = ckdout[1]
  ValueError: shape mismatch: value array of shape (240,4) could not be broadcast to indexing result of shape (240,5)
```

#### Versions:

> scanpy==1.4.6 anndata==0.7.1 umap==0.4.1 numpy==1.18.2 scipy==1.4.1 pandas==1.0.3 scikit-learn==0.22.2.post1 statsmodels==0.11.1

**Comment by dweemx** [comment]
`neighbors_within_batch` was too high (one group had 2 cells)
