### ISSUE TITLE
install of scanpy dredges up anndata's scipy issue

### ISSUE THREAD

**Issue by mathog** [scverse/scanpy#1273]
```pytb
package=scanpy
pversion=1.5.1 #found in docs/release-latest.rst after git download
TOPDIR=/usr/common/modules/el8/x86_64/software/${package}/${pversion}-CentOS-vanilla
cd /usr/common/src
git clone https://github.com/theislab/scanpy.git
cd scanpy
module load python3-libraries #for PYTHONPATH
python3 ./setup.py install \
  --install-scripts=$TOPDIR/bin --prefix /usr/common  \
  2>&1 | tee  ../install_2020_06_10.log
#setup a module "scanpy" which puts $TOPDIR/bin on path and
#defines PYTHONPATH, then do
module load scanpy
scanpy
/home/common/lib/python3.6/site-packages/anndata/base.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "/usr/common/modules/el8/x86_64/software/scanpy/1.5.1-CentOS-vanilla/bin/scanpy", line 11, in <module>
    load_entry_point('scanpy==1.5.2.dev7+ge33a2f33', 'console_scripts', 'scanpy')()
  File "/usr/common/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/common/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/usr/common/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/usr/common/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/common/lib/python3.6/site-packages/scanpy-1.5.2.dev7+ge33a2f33-py3.6.egg/scanpy/__init__.py", line 3, in <module>
    from ._utils import pkg_version, check_versions, annotate_doc_types
  File "/home/common/lib/python3.6/site-packages/scanpy-1.5.2.dev7+ge33a2f33-py3.6.egg/scanpy/_utils.py", line 17, in <module>
    from anndata import AnnData
  File "/home/common/lib/python3.6/site-packages/anndata/__init__.py", line 1, in <module>
    from .base import AnnData
  File "/home/common/lib/python3.6/site-packages/anndata/base.py", line 21, in <module>
    from scipy.sparse.sputils import IndexMixin
ImportError: cannot import name 'IndexMixin'
```

```bash
#pip3 install works any better?
pip3 install scanpy   --target $PYTHONPATH --upgrade
pip3 install scanpy-scripts   --target $PYTHONPATH --upgrade
scanpy
#same thing
```

There are multiple versions of many packages in PYTHONPATH and at some point it seems to be picking the wrong ones.  Examples:

```bash
ls -1 $PYTHONPATH | grep scanpy
scanpy
scanpy-1.4.3.dist-info
scanpy-1.4.3-py3.6.egg
scanpy-1.4.6.dist-info
scanpy-1.5.1.dist-info
scanpy-1.5.2.dev7+ge33a2f33-py3.6.egg
scanpy_scripts
scanpy_scripts-0.2.10.dist-info
scanpy_scripts-0.2.10-py3.6.egg
ls -1 $PYTHONPATH | grep scipy
scipy
scipy-1.2.3.dist-info
scipy-1.2.3-py3.6-linux-x86_64.egg
scipy-1.4.1.dist-info
ls -1 $PYTHONPATH | grep anndata
anndata
anndata-0.6.19.dist-info
anndata-0.6.19-py3.6.egg
anndata-0.7.1.dist-info
anndata-0.7.3.dist-info
```

#### Versions:

> ...
current git (plus others).

**Comment by ivirshup** [comment]
I think your issue here is due to having multiple versions of various packages in your path. In general, that will cause problems. I think I can only recommend creating an isolated environment using something like `conda` or `virtualenv` and say that installing with `pip` tends to have the fewest problems.

**Comment by mathog** [comment]
It still does not work for me, even in a virtualenv.  I always get:
```

  #Using legacy setup.py install for umap-learn, since package 'wheel' is not installed.
  #ERROR: umap-learn 0.4.6 has requirement scipy>=1.3.1, but you'll have scipy 1.2.3 which is incompatible.

  cd /usr/common/lib/python3.6/Envs
  rm -rf ~/.cache/pip #make download clearer
  python3 -m venv scanpy_scripts
  source scanpy_scripts/bin/activate
  python -m pip install -U pip
  python -m pip install scanpy_scripts
  #same error
  python -m pip install -U setuptools #39.2 -> 47.3.1
  python -m pip install scanpy_scripts
  #same error
  python -m pip install -U wheel
  python -m pip install scanpy_scripts
  #same error
  echo $PYTHONPATH
  #is blank

```

**Comment by mathog** [comment]
Also, set up johnnydep and then do:

`johnnydep --output-format pinned scanpy_scripts
`
and after trundling for a very long time and emitting a lot of messages it gives up with:

```

Given no hashes to check 0 links for project 'scipy': discarding no candidates
ERROR: Could not find a version that satisfies the requirement scipy<1.3.0,>=0.19.1,>=1.0,>=1.0.1,>=1.2.0,>=1.3.1,~=1.0 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0rc2, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0)
ERROR: No matching distribution found for scipy<1.3.0,>=0.19.1,>=1.0,>=1.0.1,>=1.2.0,>=1.3.1,~=1.0

```

**Comment by ivirshup** [comment]
It's definitely a problem that you are seeing all of these version restrictions at once. This may be related to having too many entries in your PYTHONPATH environment variable. `PYTHONPATH` should probably just be empty, since python already knows to look where pip installs packages.

**Comment by mathog** [comment]
Look at the virtualenv example - PYTHONPATH was empty.  The johnnydep application does not actually do an install, it just downloads all the pieces a package calls for and looks at all the listed requirements - and it gives the same version restriction conflict as an actual installation attemp.

**Comment by flying-sheep** [comment]
Which package has the `scipy<1.3.0` dependency?

**Comment by mathog** [comment]
It seems to be scanpy-scripts itself.

johnnydep analysis shows these (99% of lines removed):
```

2020-07-20 18:57:50 [info     ] init johnnydist                [johnnydep.lib] dist=scipy<1.3.0,>=1.2.0 parent=scanpy-scripts
2020-07-20 18:58:10 [info     ] init johnnydist                [johnnydep.lib] dist=scipy~=1.0 parent=anndata<0.6.20
2020-07-20 18:59:17 [info     ] init johnnydist                [johnnydep.lib] dist=scipy~=1.0 parent=anndata>=0.6.15
2020-07-20 18:59:26 [info     ] init johnnydist                [johnnydep.lib] dist=scipy>=0.19.1 parent=scikit-learn>=0.19.1
2020-07-20 18:59:58 [info     ] init johnnydist                [johnnydep.lib] dist=scipy>=1.3.1 parent=umap-learn>=0.3.0
```

and later

```
2020-07-20 19:00:14 [info     ] merged specs                   [johnnydep.lib] dist=scanpy-scripts extras=
set() name=scipy spec=<SpecifierSet('<1.3.0,>=0.19.1,>=1.0,>=1.0.1,>=1.2.0,>=1.3.1,~=1.0', prereleases=True)>

```

It cannot match both <1.3.0 and >= 1.3.1, and eventually bails out with:

```
ERROR: No matching distribution found for scipy<1.3.0,>=0.19.1,>=1.0,>=1.0.1,>=1.2.0,>=1.3.1,~=1.0
pip._internal.exceptions.DistributionNotFound: No matching distribution found for scipy<1.3.0,>=0.19.1,>=1.0,>=1.0.1,>=1.2.0,>=1.3.1,~=1.0
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'wheel', '-vvv', '--no-deps', '--no-cache-dir', '--disable-pip-version-check', '--pro
gress-bar=off', 'scipy<1.3.0,>=0.19.1,>=1.0,>=1.0.1,>=1.2.0,>=1.3.1,~=1.0']' returned non-zero exit status 1.
```

**Comment by flying-sheep** [comment]
Yeah, please file your issue with [scanpy-scripts](https://github.com/ebi-gene-expression-group/scanpy-scripts) then, and ask them why they want an old scipy version and if they can upgrade their code to work with scipy 1.3+
