### ISSUE TITLE
ImportError: libblosc.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Zifeng-L** [scverse/scanpy#1284]
I installed the package by `pip install scanpy`. When I imported it, there was such an error

```python
import scanpy as sc
```

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sibcb1/mxqianlab1/common/anaconda/envs/cnmf_env/lib/python3.6/site-packages/scanpy/__init__.py", line 36, in <module>
    from . import tools as tl
  File "/sibcb1/mxqianlab1/common/anaconda/envs/cnmf_env/lib/python3.6/site-packages/scanpy/tools/__init__.py", line 17, in <module>
    from ._sim import sim
  File "/sibcb1/mxqianlab1/common/anaconda/envs/cnmf_env/lib/python3.6/site-packages/scanpy/tools/_sim.py", line 23, in <module>
    from .. import _utils, readwrite, logging as logg
  File "/sibcb1/mxqianlab1/common/anaconda/envs/cnmf_env/lib/python3.6/site-packages/scanpy/readwrite.py", line 10, in <module>
    import tables
  File "/sibcb1/mxqianlab1/common/anaconda/envs/cnmf_env/lib/python3.6/site-packages/tables/__init__.py", line 93, in <module>
    from .utilsextension import (
ImportError: libblosc.so.1: cannot open shared object file: No such file or directory

```

#### Versions:

> version 1.5.1

**Comment by ivirshup** [comment]
Are you able to run `import tables` in this environment? If not, I think the issue will be with installation of the `pytables` package.
