### ISSUE TITLE
`wx` module missing after installing scanpy on macOS

### ISSUE THREAD

**Issue by chris-rands** [scverse/scanpy#1302]
`wx` appears to be a missing scanpy dependancy linked to matplotlib when installing on macOS

```python
>>> import scanpy as sc
```

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/path/lib/python3.7/site-packages/scanpy/__init__.py", line 38, in <module>
    from . import plotting as pl
  File "/miniconda3/envs/path/lib/python3.7/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import scatter, violin, ranking, clustermap, stacked_violin, heatmap, dotplot, matrixplot, tracksplot, dendrogram, correlation_matrix
  File "/miniconda3/envs/path/lib/python3.7/site-packages/scanpy/plotting/_anndata.py", line 16, in <module>
    from matplotlib import pyplot as pl
  File "/miniconda3/envs/path/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2282, in <module>
    switch_backend(rcParams["backend"])
  File "/miniconda3/envs/path/lib/python3.7/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/miniconda3/envs/path/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/miniconda3/envs/path/lib/python3.7/site-packages/matplotlib/backends/backend_wxagg.py", line 1, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'
```

The solution is simple, install `wxPython` https://pypi.org/project/wxPython/. However, it would be nice if scanpy could handle this OS-specific dependancy

#### Versions:
The latest scanpy version (1.5.1) installed via conda- of course I cannot print the versions since the scanpy import fails, other details;

```
>>> import sys; print(sys.version)
3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:33:30) 
[Clang 9.0.1 ]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-17.7.0-x86_64-i386-64bit
```
...
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G11023
```

**Comment by gokceneraslan** [comment]
Are you sure you haven't set wxpython as the matplotlib backend somehow? Many of us use scanpy on macOS but I never manually installed wxpython...

**Comment by chris-rands** [comment]
Thanks, what is the default backend on macOS? I only install matplotlib via the scanpy/anndata depenancies in a conda environment (and `MPLBACKEND` is unset). Upon installing wxpython, I can confirm the used backend

```
>>> matplotlib.__version__
'3.2.2'
>>> matplotlib.rcParams['backend']
'WXAgg'
>>> matplotlib.get_backend()
'WXAgg'
```

**Comment by gokceneraslan** [comment]
`matplotlib.rcParams['backend']` gives `MacOSX` on my laptop. Sorry, no idea why mpl picks wx and fails. But I think this is not a scanpy issue.
