### ISSUE TITLE
Scanpy==1.6 cannot be imported for anndata<0.7.4

### ISSUE THREAD

**Issue by WeilerP** [scverse/scanpy#1439]
## Description

`scanpy==1.6` cannot be used with `anndata<=0.7.3` due to an import error in `scanpy/__init__.py` as `concat` cannot be imported from `anndata`.

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy as sc
```

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/scanpy_bug/lib/python3.8/site-packages/scanpy/__init__.py", line 41, in <module>
    from anndata import AnnData, concat
ImportError: cannot import name 'concat' from 'anndata' (/opt/anaconda3/envs/scanpy_bug/lib/python3.8/site-packages/anndata/__init__.py)
```

#### Versions

<details>

```
-----
anndata     0.7.3
scanpy      1.6.0
sinfo       0.3.1
-----
anndata             0.7.3
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
get_version         2.1
h5py                2.10.0
igraph              0.8.2
joblib              0.15.1
kiwisolver          1.2.0
legacy_api_wrap     1.2
leidenalg           0.8.2
llvmlite            0.33.0
louvain             0.7.0
matplotlib          3.2.1
mpl_toolkits        NA
natsort             7.0.1
numba               0.50.0
numexpr             2.7.1
numpy               1.18.5
packaging           20.4
pandas              1.1.2
pkg_resources       NA
pyparsing           2.4.7
pytz                2020.1
scanpy              1.6.0
scipy               1.4.1
setuptools_scm      NA
sinfo               0.3.1
six                 1.15.0
sklearn             0.23.1
tables              3.6.1
texttable           1.6.2
wcwidth             0.2.4
yaml                5.3.1
-----
Python 3.8.3 (default, May 19 2020, 13:54:14) [Clang 10.0.0 ]
macOS-10.15.7-x86_64-i386-64bit
12 logical CPU cores, i386
-----
Session information updated at 2020-10-03 14:22
```

</details>

**Comment by jhrdt** [comment]
Hej,

I stumbled upon your issue.

Test for my PR #1440:

```
python3 -m venv venv
source venv/bin/activate
pip install -e . 
pip install "anndata<=0.7.3"
python3 -c "import scanpy as sc"
```

**Comment by WeilerP** [comment]
Thank you for your PR!

I am, however, not sure if #1440 suffices: For one, `anndata/_core/merge.py:concat` only exists since `anndata==0.7.2a1`, so the version of `anndata` in `scanpy/requirements.txt`  has to be bumped up to at least `anndata>=0.7.2a1` (`anndata>=0.7.2` would probably be better). In addition, prior to `anndata==0.7.4`, many bug fixes have been implemented for `anndata/_core/merge.py:concat`. Begs the question if a prior version is even desirable / should be supported.

@ivirshup, any thoughts on this since you implemented the function?

**Comment by ivirshup** [comment]
You're totally right. Opening a PR to bump the required version now.

**Comment by balthasar0810** [comment]
I am still having this issue. How can this be solved for non-hackers?

**Comment by rlittman16** [comment]
its working for me by using an older scanpy version

`pip install scanpy==0.2.3.5`

**Comment by ivirshup** [comment]
@balthasar0810, are you running into this with an up to date version of anndata?

**Comment by ryan-williams** [comment]
I had a false alarm related to this just now (I thought I was on recent anndata+scanpy versions, but a defunct older clone of anndata was sneaking onto my `$PYTHONPATH`).

Confirming it's fixed:

**Dockerfile:**
```Dockerfile
FROM python:3.8.5
ARG anndata
ARG scanpy
RUN pip install anndata==${anndata} scanpy==${scanpy}
ENTRYPOINT ["python","-c","import scanpy"]
```

**Works:**
```bash
docker build --build-arg anndata=0.7.5 --build-arg scanpy=1.7.1 -t scanpy . && docker run scanpy  # ✅
```
**Fails:**
```bash
docker build --build-arg anndata=0.7.3 --build-arg scanpy=1.6.1 -t scanpy . && docker run scanpy  # ❌
# Traceback (most recent call last):
#   File "<string>", line 1, in <module>
#   File "/usr/local/lib/python3.8/site-packages/scanpy/__init__.py", line 41, in <module>
#     from anndata import AnnData, concat
# ImportError: cannot import name 'concat' from 'anndata' (/usr/local/lib/python3.8/site-packages/anndata/__init__.py)
```
