### ISSUE TITLE
Fail to install scanpy by pip

### ISSUE THREAD

**Issue by ttgump** [scverse/scanpy#148]
Hi everyone,
I am using pip3 to install scanpy, this is the error message:

<details>

```pytb
File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/site-packages/setuptools-18.3.2-py3.6.egg/setuptools/command/build_py.py", line 94, in find_data_files
  TypeError: must be str, not list

  ----------------------------------------
  Failed building wheel for scanpy
  Running setup.py clean for scanpy
Failed to build scanpy
Installing collected packages: scanpy, decorator
  Running setup.py install for scanpy ... error
    Complete output from command /global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/xs-ttgump/pip-install-xpuhp0co/scanpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/xs-ttgump/pip-record-v4z7bmhr/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/scanpy
    copying scanpy/logging.py -> build/lib/scanpy
    copying scanpy/exporting.py -> build/lib/scanpy
    copying scanpy/_version.py -> build/lib/scanpy
    copying scanpy/utils.py -> build/lib/scanpy
    copying scanpy/__init__.py -> build/lib/scanpy
    copying scanpy/settings.py -> build/lib/scanpy
    copying scanpy/readwrite.py -> build/lib/scanpy
    creating build/lib/scanpy/tools
    copying scanpy/tools/dpt.py -> build/lib/scanpy/tools
    copying scanpy/tools/paga.py -> build/lib/scanpy/tools
    copying scanpy/tools/louvain.py -> build/lib/scanpy/tools
    copying scanpy/tools/_utils.py -> build/lib/scanpy/tools
    copying scanpy/tools/pca.py -> build/lib/scanpy/tools
    copying scanpy/tools/umap.py -> build/lib/scanpy/tools
    copying scanpy/tools/sim.py -> build/lib/scanpy/tools
    copying scanpy/tools/tsne.py -> build/lib/scanpy/tools
    copying scanpy/tools/__init__.py -> build/lib/scanpy/tools
    copying scanpy/tools/draw_graph.py -> build/lib/scanpy/tools
    copying scanpy/tools/score_genes.py -> build/lib/scanpy/tools
    copying scanpy/tools/_tsne_fix.py -> build/lib/scanpy/tools
    copying scanpy/tools/rank_genes_groups.py -> build/lib/scanpy/tools
    copying scanpy/tools/diffmap.py -> build/lib/scanpy/tools
    copying scanpy/tools/top_genes.py -> build/lib/scanpy/tools
    creating build/lib/scanpy/sim_models
    copying scanpy/sim_models/__init__.py -> build/lib/scanpy/sim_models
    creating build/lib/scanpy/datasets
    copying scanpy/datasets/__init__.py -> build/lib/scanpy/datasets
    copying scanpy/datasets/api_without_datasets.py -> build/lib/scanpy/datasets
    creating build/lib/scanpy/neighbors
    copying scanpy/neighbors/__init__.py -> build/lib/scanpy/neighbors
    creating build/lib/scanpy/preprocessing
    copying scanpy/preprocessing/recipes.py -> build/lib/scanpy/preprocessing
    copying scanpy/preprocessing/simple.py -> build/lib/scanpy/preprocessing
    copying scanpy/preprocessing/__init__.py -> build/lib/scanpy/preprocessing
    creating build/lib/scanpy/plotting
    copying scanpy/plotting/rcmod.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/palettes.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/utils.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/top_genes_visual.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/__init__.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/anndata.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/preprocessing.py -> build/lib/scanpy/plotting
    creating build/lib/scanpy/api
    copying scanpy/api/datasets.py -> build/lib/scanpy/api
    copying scanpy/api/pl.py -> build/lib/scanpy/api
    copying scanpy/api/pp.py -> build/lib/scanpy/api
    copying scanpy/api/export_to.py -> build/lib/scanpy/api
    copying scanpy/api/__init__.py -> build/lib/scanpy/api
    copying scanpy/api/tl.py -> build/lib/scanpy/api
    creating build/lib/scanpy/neighbors/umap
    copying scanpy/neighbors/umap/utils.py -> build/lib/scanpy/neighbors/umap
    copying scanpy/neighbors/umap/distances.py -> build/lib/scanpy/neighbors/umap
    copying scanpy/neighbors/umap/umap_.py -> build/lib/scanpy/neighbors/umap
    copying scanpy/neighbors/umap/__init__.py -> build/lib/scanpy/neighbors/umap
    copying scanpy/neighbors/umap/sparse.py -> build/lib/scanpy/neighbors/umap
    creating build/lib/scanpy/plotting/tools
    copying scanpy/plotting/tools/paga.py -> build/lib/scanpy/plotting/tools
    copying scanpy/plotting/tools/__init__.py -> build/lib/scanpy/plotting/tools
    running egg_info
    writing scanpy.egg-info/PKG-INFO
    writing dependency_links to scanpy.egg-info/dependency_links.txt
    writing requirements to scanpy.egg-info/requires.txt
    writing top-level names to scanpy.egg-info/top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'scanpy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'scanpy.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/xs-ttgump/pip-install-xpuhp0co/scanpy/setup.py", line 50, in <module>
        'Topic :: Scientific/Engineering :: Visualization',
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/site-packages/setuptools-18.3.2-py3.6.egg/setuptools/command/install.py", line 61, in run
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/xs-ttgump/pip-install-xpuhp0co/scanpy/versioneer.py", line 1555, in run
        _build_py.run(self)
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/site-packages/setuptools-18.3.2-py3.6.egg/setuptools/command/build_py.py", line 47, in run
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/site-packages/setuptools-18.3.2-py3.6.egg/setuptools/command/build_py.py", line 103, in build_package_data
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/site-packages/setuptools-18.3.2-py3.6.egg/setuptools/command/build_py.py", line 59, in __getattr__
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/site-packages/setuptools-18.3.2-py3.6.egg/setuptools/command/build_py.py", line 86, in _get_data_files
      File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/lib/python3.6/site-packages/setuptools-18.3.2-py3.6.egg/setuptools/command/build_py.py", line 94, in find_data_files
    TypeError: must be str, not list

    ----------------------------------------
Command "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/Python/3.6.0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/xs-ttgump/pip-install-xpuhp0co/scanpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/xs-ttgump/pip-record-v4z7bmhr/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/xs-ttgump/pip-install-xpuhp0co/scanpy/
```

**Comment by gokceneraslan** [comment]
Difficult to say something from the trace, it might be related to old setuptools version. You may try updating it. Alternatively, you can set up a [miniconda installation](https://scanpy.readthedocs.io/en/latest/installation.html#installing-miniconda) in your home folder to have more up-to-date packages.

**Comment by falexwolf** [comment]
Thanks Gökcen... Yes, try `pip3 install --upgrade setuptools` or `pip` if this defaults to Python 3 already...

**Comment by LKremer** [comment]
My coworker and I had the same issue as @ttgump. Upgrading setuptools fixed it. Maybe it's worth adding a note to the installation troubleshooting documentation?
