### ISSUE TITLE
error in scanpy first tutorial

### ISSUE THREAD

**Issue by ghost** [scverse/scanpy#158]
Hi, I'm trying scanpy for the first time, but following the first tutorial I got the error below.
Any idea of what is happening?

```pytb
>>> filter_result = sc.pp.filter_genes_dispersion(
...     adata.X, min_mean=0.0125, max_mean=3, min_disp=0.5)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/anaconda3/envs/tiget/lib/python3.6/site-packages/scanpy/preprocessing/simple.py", line 328, in filter_genes_dispersion
    disp_std_bin[one_gene_per_bin] = disp_mean_bin[one_gene_per_bin]
  File "/opt/anaconda3/envs/tiget/lib/python3.6/site-packages/pandas/core/series.py", line 938, in __setitem__
    setitem(key, value)
  File "/opt/anaconda3/envs/tiget/lib/python3.6/site-packages/pandas/core/series.py", line 929, in setitem
    self._where(~key, value, inplace=True)
  File "/opt/anaconda3/envs/tiget/lib/python3.6/site-packages/pandas/core/generic.py", line 7539, in _where
    level=level, fill_value=np.nan)
  File "/opt/anaconda3/envs/tiget/lib/python3.6/site-packages/pandas/core/series.py", line 3248, in align
    broadcast_axis=broadcast_axis)
  File "/opt/anaconda3/envs/tiget/lib/python3.6/site-packages/pandas/core/generic.py", line 7366, in align
    fill_axis=fill_axis)
  File "/opt/anaconda3/envs/tiget/lib/python3.6/site-packages/pandas/core/generic.py", line 7435, in _align_series
    return_indexers=True)
  File "/opt/anaconda3/envs/tiget/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3772, in join
    return_indexers=return_indexers)
  File "/opt/anaconda3/envs/tiget/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4012, in _join_monotonic
    ridx = self._left_indexer_unique(sv, ov)
  File "pandas/_libs/join_helper.pxi", line 774, in pandas._libs.join.left_join_indexer_unique_object
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'signed char'
```

**Comment by ghost** [comment]
The same exact error also happens using the docker image suggested on the web site
fastgenomics/scanpy

**Comment by falexwolf** [comment]
Hm, this is really strange. Sorry about this.

The docker image might be out-of-date now - you compiled, @flying-sheep, what do you think?

But you shouldn't need the docker image to exactly reproduce the results. Which versions do you run?

The latest version of the tutorial says
```
scanpy==1.0.2 anndata==0.5.8 numpy==1.14.1 scipy==1.0.0 pandas==0.22.0 scikit-learn==0.19.1 statsmodels==0.8.0 python-igraph==0.7.1 louvain==0.6.1 
```

Your error is a Pandas error - do you run an older or more recent version of Pandas that might cause the problem?

**Comment by falexwolf** [comment]
Type `pip install pandas==0.22.0` to get the same version and run the notebook again... Of course, if  we are not compatible with more recent versions of pandas, we'll immediately fix the problem.

**Comment by falexwolf** [comment]
Unfortunately, we had a prerelease with a bug in `rank_genes_groups_violin`... on PyPI... the current prelease `1.1a2` should run almost stable... 1.1 will be out in the next couple of days.

**Comment by ghost** [comment]
Hi, here my settings:

scanpy==1.0.4 anndata==0.6.1 numpy==1.14.2 scipy==1.1.0 pandas==0.23.0 
scikit-learn==0.19.1 statsmodels==0.9.0 python-igraph==0.7.1

Ivan

**Comment by falexwolf** [comment]
Ok, it's related to pandas 0.23 - runs on pandas 0.22. Don't know what happened but I'll fix this tomorrow. In the meanwhile you could `pip install pandas==0.22.0`.

**Comment by flying-sheep** [comment]
> Unfortunately, we had a prerelease with a bug

the dangers of installing prereleases :wink:

the docker image is on 1.1a1 though :innocent:

**Comment by falexwolf** [comment]
I was wrong. The pandas 0.23 issue is not related to the prerelease... Unfortunately, I still haven't found the time to figure out what is going wrong... but it's on top of the list.

**Comment by fidelram** [comment]
The solution do downgrade to pandas=0.22 worked for me. Thanks
