### ISSUE TITLE
spatial dataset download issue

### ISSUE THREAD

**Issue by lu77777777** [scverse/scanpy#1714]
- [x] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---
Hi, I tried to use the tutorial of  Analysis and visualization of spatial transcriptomics data but is seems have some problems

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
# Your code here
```when I run 
adata = sc.datasets.visium_sge(sample_id="V1_Human_Lymph_Node")


```pytb
[Paste the error output produced by the above code here]
```
Traceback (most recent call last):
  File "/tmp/pycharm_project_346/spatial.py", line 11, in <module>
    adata = sc.datasets.visium_sge(sample_id="V1_Human_Lymph_Node")
  File "/data/lu/anaconda3/envs/spatial_t/lib/python3.8/site-packages/scanpy/datasets/_datasets.py", line 367, in visium_sge
    _download_visium_dataset(sample_id)
  File "/data/lu/anaconda3/envs/spatial_t/lib/python3.8/site-packages/scanpy/datasets/_datasets.py", line 325, in _download_visium_dataset
    _utils.check_presence_download(
  File "/data/lu/anaconda3/envs/spatial_t/lib/python3.8/site-packages/scanpy/_utils.py", line 604, in check_presence_download
    _download(backup_url, filename)
  File "/data/lu/anaconda3/envs/spatial_t/lib/python3.8/site-packages/scanpy/readwrite.py", line 905, in _download
    urlretrieve(url, str(path), reporthook=update_to)
  File "/data/lu/anaconda3/envs/spatial_t/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/data/lu/anaconda3/envs/spatial_t/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/data/lu/anaconda3/envs/spatial_t/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/data/lu/anaconda3/envs/spatial_t/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/data/lu/anaconda3/envs/spatial_t/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/data/lu/anaconda3/envs/spatial_t/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/data/lu/anaconda3/envs/spatial_t/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Process finished with exit code 1

#### Versions

<details>
scanpy==1.5.0 anndata==0.7.1 umap==0.4.2 numpy==1.18.1 scipy==1.4.1 pandas==1.0.3 scikit-learn==0.22.1 statsmodels==0.11.0

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>

**Comment by ivirshup** [comment]
It looks like you've got an outdated version of scanpy (1.5.0), this should be fixed in more recent releases by #1334.
