### ISSUE TITLE
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)

### ISSUE THREAD

**Issue by 117999** [scverse/scanpy#1756]

**Comment by 117999** [comment]
Hello,
I am now facing a problem of failure in computing neighbours when using scanpy or scvelo
when I tried to use the 


`sc.pp.neighbors(labelled, n_neighbors=5, n_pcs=4)`
or
`scv.pp.moments(raw, n_pcs=30, n_neighbors=30)`
it will always reports that

```pytb
`computing neighbors
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/errors.py in new_error_context(fmt_, *args, **kwargs)
    743     try:
--> 744         yield
    745     except NumbaError as e:

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/lowering.py in lower_block(self, block)
    229                                    loc=self.loc, errcls_=defaulterrcls):
--> 230                 self.lower_inst(inst)
    231         self.post_block(block)

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/lowering.py in lower_inst(self, inst)
    327             val = self.lower_assign(ty, inst)
--> 328             self.storevar(val, inst.target.name)
    329 

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/lowering.py in storevar(self, value, name)
   1277                                                           name=name)
-> 1278             raise AssertionError(msg)
   1279 

AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-37-db298150880d> in <module>
----> 1 scv.pp.moments(raw, n_pcs=30, n_neighbors=30)

~/.conda/envs/rpy/lib/python3.9/site-packages/scvelo/preprocessing/moments.py in moments(data, n_neighbors, n_pcs, mode, method, use_rep, use_highly_variable, copy)
     62 
     63     if n_neighbors is not None and n_neighbors > get_n_neighs(adata):
---> 64         neighbors(
     65             adata,
     66             n_neighbors=n_neighbors,

~/.conda/envs/rpy/lib/python3.9/site-packages/scvelo/preprocessing/neighbors.py in neighbors(adata, n_neighbors, n_pcs, use_rep, use_highly_variable, knn, random_state, method, metric, metric_kwds, num_threads, copy)
    161             warnings.simplefilter("ignore")
    162             neighbors = Neighbors(adata)
--> 163             neighbors.compute_neighbors(
    164                 n_neighbors=n_neighbors,
    165                 knn=knn,

~/.conda/envs/rpy/lib/python3.9/site-packages/scanpy/neighbors/__init__.py in compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    748             # we need self._distances also for method == 'gauss' if we didn't
    749             # use dense distances
--> 750             self._distances, self._connectivities = _compute_connectivities_umap(
    751                 knn_indices,
    752                 knn_distances,

~/.conda/envs/rpy/lib/python3.9/site-packages/scanpy/neighbors/__init__.py in _compute_connectivities_umap(knn_indices, knn_dists, n_obs, n_neighbors, set_op_mix_ratio, local_connectivity)
    353         # umap 0.5.0
    354         warnings.filterwarnings("ignore", message=r"Tensorflow not installed")
--> 355         from umap.umap_ import fuzzy_simplicial_set
    356 
    357     X = coo_matrix(([], ([], [])), shape=(n_obs, 1))

~/.conda/envs/rpy/lib/python3.9/site-packages/umap/__init__.py in <module>
----> 1 from .umap_ import UMAP
      2 
      3 # Workaround: https://github.com/numba/numba/issues/3341
      4 import numba
      5 

~/.conda/envs/rpy/lib/python3.9/site-packages/umap/umap_.py in <module>
     52 from umap.spectral import spectral_layout
     53 from umap.utils import deheap_sort, submatrix
---> 54 from umap.layouts import (
     55     optimize_layout_euclidean,
     56     optimize_layout_generic,

~/.conda/envs/rpy/lib/python3.9/site-packages/umap/layouts.py in <module>
     37     },
     38 )
---> 39 def rdist(x, y):
     40     """Reduced Euclidean distance.
     41 

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/decorators.py in wrapper(func)
    219             with typeinfer.register_dispatcher(disp):
    220                 for sig in sigs:
--> 221                     disp.compile(sig)
    222                 disp.disable_compile()
    223         return disp

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/dispatcher.py in compile(self, sig)
    907                 with ev.trigger_event("numba:compile", data=ev_details):
    908                     try:
--> 909                         cres = self._compiler.compile(args, return_type)
    910                     except errors.ForceLiteralArg as e:
    911                         def folded(args, kws):

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/dispatcher.py in compile(self, args, return_type)
     77 
     78     def compile(self, args, return_type):
---> 79         status, retval = self._compile_cached(args, return_type)
     80         if status:
     81             return retval

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_cached(self, args, return_type)
     91 
     92         try:
---> 93             retval = self._compile_core(args, return_type)
     94         except errors.TypingError as e:
     95             self._failed_cache[key] = e

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_core(self, args, return_type)
    104 
    105         impl = self._get_implementation(args, {})
--> 106         cres = compiler.compile_extra(self.targetdescr.typing_context,
    107                                       self.targetdescr.target_context,
    108                                       impl,

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    604     pipeline = pipeline_class(typingctx, targetctx, library,
    605                               args, return_type, flags, locals)
--> 606     return pipeline.compile_extra(func)
    607 
    608 

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/compiler.py in compile_extra(self, func)
    351         self.state.lifted = ()
    352         self.state.lifted_from = None
--> 353         return self._compile_bytecode()
    354 
    355     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/compiler.py in _compile_bytecode(self)
    413         """
    414         assert self.state.func_ir is None
--> 415         return self._compile_core()
    416 
    417     def _compile_ir(self):

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/compiler.py in _compile_core(self)
    393                 self.state.status.fail_reason = e
    394                 if is_final_pipeline:
--> 395                     raise e
    396         else:
    397             raise CompilerError("All available pipelines exhausted")

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/compiler.py in _compile_core(self)
    384             res = None
    385             try:
--> 386                 pm.run(self.state)
    387                 if self.state.cr is not None:
    388                     break

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/compiler_machinery.py in run(self, state)
    337                     (self.pipeline_name, pass_desc)
    338                 patched_exception = self._patch_error(msg, e)
--> 339                 raise patched_exception
    340 
    341     def dependency_analysis(self):

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/compiler_machinery.py in run(self, state)
    328                 pass_inst = _pass_registry.get(pss).pass_inst
    329                 if isinstance(pass_inst, CompilerPass):
--> 330                     self._runPass(idx, pass_inst, state)
    331                 else:
    332                     raise BaseException("Legacy pass in use")

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     33         def _acquire_compile_lock(*args, **kwargs):
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock
     37 

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/compiler_machinery.py in _runPass(self, index, pss, internal_state)
    287             mutated |= check(pss.run_initialization, internal_state)
    288         with SimpleTimer() as pass_time:
--> 289             mutated |= check(pss.run_pass, internal_state)
    290         with SimpleTimer() as finalize_time:
    291             mutated |= check(pss.run_finalizer, internal_state)

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/compiler_machinery.py in check(func, compiler_state)
    260 
    261         def check(func, compiler_state):
--> 262             mangled = func(compiler_state)
    263             if mangled not in (True, False):
    264                 msg = ("CompilerPass implementations should return True/False. "

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/typed_passes.py in run_pass(self, state)
    461 
    462         # TODO: Pull this out into the pipeline
--> 463         NativeLowering().run_pass(state)
    464         lowered = state['cr']
    465         signature = typing.signature(state.return_type, *state.args)

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/typed_passes.py in run_pass(self, state)
    382                 lower = lowering.Lower(targetctx, library, fndesc, interp,
    383                                        metadata=metadata)
--> 384                 lower.lower()
    385                 if not flags.no_cpython_wrapper:
    386                     lower.create_cpython_wrapper(flags.release_gil)

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/lowering.py in lower(self)
    134         if self.generator_info is None:
    135             self.genlower = None
--> 136             self.lower_normal_function(self.fndesc)
    137         else:
    138             self.genlower = self.GeneratorLower(self)

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/lowering.py in lower_normal_function(self, fndesc)
    188         # Init argument values
    189         self.extract_function_arguments()
--> 190         entry_block_tail = self.lower_function_body()
    191 
    192         # Close tail of entry block

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/lowering.py in lower_function_body(self)
    214             bb = self.blkmap[offset]
    215             self.builder.position_at_end(bb)
--> 216             self.lower_block(block)
    217         self.post_lower()
    218         return entry_block_tail

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/lowering.py in lower_block(self, block)
    228             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    229                                    loc=self.loc, errcls_=defaulterrcls):
--> 230                 self.lower_inst(inst)
    231         self.post_block(block)
    232 

~/.conda/envs/rpy/lib/python3.9/contextlib.py in __exit__(self, type, value, traceback)
    133                 value = type()
    134             try:
--> 135                 self.gen.throw(type, value, traceback)
    136             except StopIteration as exc:
    137                 # Suppress StopIteration *unless* it's the same exception that

~/.conda/envs/rpy/lib/python3.9/site-packages/numba/core/errors.py in new_error_context(fmt_, *args, **kwargs)
    749         newerr = errcls(e).add_context(_format_msg(fmt_, args, kwargs))
    750         tb = sys.exc_info()[2] if numba.core.config.FULL_TRACEBACKS else None
--> 751         raise newerr.with_traceback(tb)
    752 
    753 

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Storing i64 to ptr of i32 ('dim'). FE type int32

File "../../../../../../../.conda/envs/rpy/lib/python3.9/site-packages/umap/layouts.py", line 52:
def rdist(x, y):
    <source elided>
    result = 0.0
    dim = x.shape[0]
    ^

During: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at /public/home/ycxiang_zju/.conda/envs/rpy/lib/python3.9/site-packages/umap/layouts.py (52)
```
​
sc.pp.filter_cells(unspliced, min_genes=200)
dyn.pl.basic_stats(spliced)`
I am wondering how to solve this problem. Will I need to re-create a virtual environment with lower python verison?

**Comment by giovp** [comment]
which numba do you have? can you try with most recent version ?

**Comment by jbliton** [comment]
I'm running into this issue too and I have the most recent version of numba 0.53.1

Any info I can provide to help troubleshoot this?

**Comment by giovp** [comment]
It was reported also in a scvelo (see above) can you try with mumba 0.53 or 0.52?

**Comment by 117999** [comment]
Hi, I have downgrade my numab version to 0.51, it works

**Comment by jbliton** [comment]
Ok, so I downgraded to numba version 0.52.0 and that seems to be working well as of 5 minutes ago. 

Thanks for your help!

**Comment by WeilerP** [comment]
@giovp, how would you like to continue with this? We could either set an upper bound on `numba`, i.e. `numba<0.53.0`, or change how `umap-learn` is pinned. In the latter case, `umap-learn>=0.5.1` should work (see [here](https://github.com/lmcinnes/umap/releases/tag/0.5.1)). I think this approach would be best, since `numba>=0.53` supports `python>=3.9`.
Happy to open the PR if you agree. Would be good to decide on how to proceed ASAP as people keep running into issues when using `scvelo` or `cellrank`.

**Comment by giovp** [comment]
hey @WeilerP ,
> umap-learn>=0.5.1 should work (see here). I think this approach would be best, since numba>=0.53 supports python>=3.9.

I agree this is the best solution, and don't think there is any drawback from scanpy side. Can @Koncopd @ivirshup comment on this? If so, I think it would be easy to inlcude it in 1.8

**Comment by iosonofabio** [comment]
FWIW, confirming `umap-learn 0.5.1` works with `numba==0.53.1` on my machine.

**Comment by ivirshup** [comment]
This is actually something I've been meaning to bug you about @WeilerP, why does scvelo pin umap below 0.5?

@giovp I'm not sure I follow. What would change in scanpy? Shouldn't allowing newer versions of umap in scvelo get around these issues?

**Comment by giovp** [comment]
> @giovp I'm not sure I follow. What would change in scanpy? Shouldn't allowing newer versions of umap in scvelo get around these issues?

my understanding is that the issue above appearss also for `sc.pp.neighbors` and so fixing a numba version would also be useful for scanpy?

**Comment by ivirshup** [comment]
What are the conflicting versions exactly? I'm having trouble replicating.

Also, what's the exact version bounds change that's being suggested?

**Comment by giovp** [comment]
with `umap-lean==0.5.0` and `numba=0.53.1` I get a different error

```python
import scanpy as sc
adata = sc.datasets.pbmc3k_processed()
sc.pp.neighbors(adata)
```

<details>
<summary>Details</summary>

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-5d47edb05ae7> in <module>
----> 1 sc.pp.neighbors(adata)

~/Projects/scanpy/scanpy/neighbors/__init__.py in neighbors(adata, n_neighbors, n_pcs, use_rep, knn, random_state, method, metric, metric_kwds, key_added, copy)
    137         adata._init_as_actual(adata.copy())
    138     neighbors = Neighbors(adata)
--> 139     neighbors.compute_neighbors(
    140         n_neighbors=n_neighbors,
    141         knn=knn,

~/Projects/scanpy/scanpy/neighbors/__init__.py in compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    806             # we need self._distances also for method == 'gauss' if we didn't
    807             # use dense distances
--> 808             self._distances, self._connectivities = _compute_connectivities_umap(
    809                 knn_indices,
    810                 knn_distances,

~/Projects/scanpy/scanpy/neighbors/__init__.py in _compute_connectivities_umap(knn_indices, knn_dists, n_obs, n_neighbors, set_op_mix_ratio, local_connectivity)
    385         # umap 0.5.0
    386         warnings.filterwarnings("ignore", message=r"Tensorflow not installed")
--> 387         from umap.umap_ import fuzzy_simplicial_set
    388 
    389     X = coo_matrix(([], ([], [])), shape=(n_obs, 1))

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/umap/__init__.py in <module>
      1 from warnings import warn, catch_warnings, simplefilter
----> 2 from .umap_ import UMAP
      3 
      4 try:
      5     with catch_warnings():

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/umap/umap_.py in <module>
     30 import umap.distances as dist
     31 
---> 32 import umap.sparse as sparse
     33 
     34 from umap.utils import (

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/umap/sparse.py in <module>
     10 import numpy as np
     11 
---> 12 from umap.utils import norm
     13 
     14 locale.setlocale(locale.LC_NUMERIC, "C")

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/umap/utils.py in <module>
     38 
     39 @numba.njit("i4(i8[:])")
---> 40 def tau_rand_int(state):
     41     """A fast (pseudo)-random number generator.
     42 

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/numba/core/decorators.py in wrapper(func)
    219             with typeinfer.register_dispatcher(disp):
    220                 for sig in sigs:
--> 221                     disp.compile(sig)
    222                 disp.disable_compile()
    223         return disp

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/numba/core/dispatcher.py in compile(self, sig)
    907                 with ev.trigger_event("numba:compile", data=ev_details):
    908                     try:
--> 909                         cres = self._compiler.compile(args, return_type)
    910                     except errors.ForceLiteralArg as e:
    911                         def folded(args, kws):

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/numba/core/dispatcher.py in compile(self, args, return_type)
     77 
     78     def compile(self, args, return_type):
---> 79         status, retval = self._compile_cached(args, return_type)
     80         if status:
     81             return retval

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_cached(self, args, return_type)
     91 
     92         try:
---> 93             retval = self._compile_core(args, return_type)
     94         except errors.TypingError as e:
     95             self._failed_cache[key] = e

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_core(self, args, return_type)
    104 
    105         impl = self._get_implementation(args, {})
--> 106         cres = compiler.compile_extra(self.targetdescr.typing_context,
    107                                       self.targetdescr.target_context,
    108                                       impl,

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/numba/core/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    602         compiler pipeline
    603     """
--> 604     pipeline = pipeline_class(typingctx, targetctx, library,
    605                               args, return_type, flags, locals)
    606     return pipeline.compile_extra(func)

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/numba/core/compiler.py in __init__(self, typingctx, targetctx, library, args, return_type, flags, locals)
    308         config.reload_config()
    309         typingctx.refresh()
--> 310         targetctx.refresh()
    311 
    312         self.state = StateDict()

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/numba/core/base.py in refresh(self)
    282             pass
    283         self.install_registry(builtin_registry)
--> 284         self.load_additional_registries()
    285         # Also refresh typing context, since @overload declarations can
    286         # affect it.

~/miniconda3/envs/scanpy_dev/lib/python3.8/site-packages/numba/core/cpu.py in load_additional_registries(self)
     76 
     77         # load 3rd party extensions
---> 78         numba.core.entrypoints.init_all()
     79 
     80     @property

AttributeError: module 'numba' has no attribute 'core'
```

</details>

so the solution would be to pin `umap-learn==0.5.1`

**Comment by ivirshup** [comment]
If we pinned `umap-learn>=0.5.1`.1 it would be impossible to install scvelo, since [it pins umap<0.5](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/requirements.txt#L9).

We can ban umap 0.5.0 specifically. It's generally important that scanpy has a broad-ish range of versions it's comparable with, since there's a lot downstream. I'd be happy bump umap to above 0.4 though, since it has been a while for that.

**Comment by WeilerP** [comment]
> This is actually something I've been meaning to bug you about @WeilerP, why does scvelo pin umap below 0.5?

This was only a dirty hack to make our unit tests pass (see e.g. [here](https://github.com/WeilerP/scvelo/runs/2112241472?check_suite_focus=true)). It's no longer pinned on `scvelo@develop` which we plan on merging into master in the following days to tag a new version.

> We can ban umap 0.5.0 specifically. It's generally important that scanpy has a broad-ish range of versions it's comparable with, since there's a lot downstream. I'd be happy bump umap to above 0.4 though, since it has been a while for that.

I believe the problem is using `umap-learn<=0.5.0` with new `numba` versions (I think `numba>=0.53.0`).

**Comment by mdbabumiamssm** [comment]
**solution please :** 
scanpy 
During: lowering "$20call_function.7 = call $16load_global.5(dim, func=$16load_global.5, args=[Var(dim, layouts.py:52)], kws=(), vararg=None, varkwarg=None, target=None)" at C:\ProgramData\Anaconda3\lib\site-packages\umap\layouts.py

sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)
computing neighbors
    using 'X_pca' with n_pcs = 40
   
   LoweringError: Failed in nopython mode pipeline (step: native lowering)
Invalid store of i64 to i32 in <numba.core.datamodel.models.RangeModel object at 0x000001FF1D57B970> (trying to write member #1)

File "C:\ProgramData\Anaconda3\lib\site-packages\umap\layouts.py", line 53:
def rdist(x, y):
    <source elided>
    dim = x.shape[0]
    for i in range(dim):
    ^

During: lowering "$20call_function.7 = call $16load_global.5(dim, func=$16load_global.5, args=[Var(dim, layouts.py:52)], kws=(), vararg=None, varkwarg=None, target=None)" at C:\ProgramData\Anaconda3\lib\site-packages\umap\layouts.py (53)

TypeError                                 Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\numba\core\errors.py in new_error_context(fmt_, *args, **kwargs)
    822     try:
--> 823         yield
    824     except NumbaError as e:

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_block(self, block)
    264                                    loc=self.loc, errcls_=defaulterrcls):
--> 265                 self.lower_inst(inst)
    266         self.post_block(block)

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_inst(self, inst)
    438             ty = self.typeof(inst.target.name)
--> 439             val = self.lower_assign(ty, inst)
    440             argidx = None

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_assign(self, ty, inst)
    625         elif isinstance(value, ir.Expr):
--> 626             return self.lower_expr(ty, value)
    627 

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_expr(self, resty, expr)
   1161         elif expr.op == 'call':
-> 1162             res = self.lower_call(resty, expr)
   1163             return res

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_call(self, resty, expr)
    890         else:
--> 891             res = self._lower_call_normal(fnty, expr, signature)
    892 

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\lowering.py in _lower_call_normal(self, fnty, expr, signature)
   1132 
-> 1133         res = impl(self.builder, argvals, self.loc)
   1134         return res
   C:\ProgramData\Anaconda3\lib\site-packages\numba\core\base.py in __call__(self, builder, args, loc)
   1189     def __call__(self, builder, args, loc=None):
-> 1190         res = self._imp(self._context, builder, self._sig, args, loc=loc)
   1191         self._context.add_linking_libs(getattr(self, 'libs', ()))

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\base.py in wrapper(*args, **kwargs)
   1219                 kwargs.pop('loc')     # drop unused loc
-> 1220                 return fn(*args, **kwargs)
   1221 

C:\ProgramData\Anaconda3\lib\site-packages\numba\cpython\rangeobj.py in range1_impl(context, builder, sig, args)
     37         state.start = context.get_constant(int_type, 0)
---> 38         state.stop = stop
     39         state.step = context.get_constant(int_type, 1)

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\cgutils.py in __setattr__(self, field, value)
    163             return super(_StructProxy, self).__setattr__(field, value)
--> 164         self[self._datamodel.get_field_position(field)] = value
    165 

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\cgutils.py in __setitem__(self, index, value)
    187             else:
--> 188                 raise TypeError("Invalid store of {value.type} to "
    189                                 "{ptr.type.pointee} in "

TypeError: Invalid store of i64 to i32 in <numba.core.datamodel.models.RangeModel object at 0x000001FF1D57B970> (trying to write member #1)

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11084\169722070.py in <module>
----> 1 sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)

C:\ProgramData\Anaconda3\lib\site-packages\scanpy\neighbors\__init__.py in neighbors(adata, n_neighbors, n_pcs, use_rep, knn, random_state, method, metric, metric_kwds, key_added, copy)
    137         adata._init_as_actual(adata.copy())
    138     neighbors = Neighbors(adata)
--> 139     neighbors.compute_neighbors(
 140         n_neighbors=n_neighbors,
    141         knn=knn,

C:\ProgramData\Anaconda3\lib\site-packages\scanpy\neighbors\__init__.py in compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    809             # we need self._distances also for method == 'gauss' if we didn't
    810             # use dense distances
--> 811             self._distances, self._connectivities = _compute_connectivities_umap(
    812                 knn_indices,
    813                 knn_distances,

C:\ProgramData\Anaconda3\lib\site-packages\scanpy\neighbors\__init__.py in _compute_connectivities_umap(knn_indices, knn_dists, n_obs, n_neighbors, set_op_mix_ratio, local_connectivity)
    390         # umap 0.5.0
    391         warnings.filterwarnings("ignore", message=r"Tensorflow not installed")
--> 392         from umap.umap_ import fuzzy_simplicial_set
    393 
    394     X = coo_matrix(([], ([], [])), shape=(n_obs, 1))

C:\ProgramData\Anaconda3\lib\site-packages\umap\__init__.py in <module>
----> 1 from .umap_ import UMAP
      2 
      3 # Workaround: https://github.com/numba/numba/issues/3341
      4 import numba
      5 

C:\ProgramData\Anaconda3\lib\site-packages\umap\umap_.py in <module>
     52 from umap.spectral import spectral_layout
     53 from umap.utils import deheap_sort, submatrix
---> 54 from umap.layouts import (
     55     optimize_layout_euclidean,
     56     optimize_layout_generic,

C:\ProgramData\Anaconda3\lib\site-packages\umap\layouts.py in <module>
     37     },
     38 )
     ---> 39 def rdist(x, y):
     40     """Reduced Euclidean distance.
     41 

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\decorators.py in wrapper(func)
    217             with typeinfer.register_dispatcher(disp):
    218                 for sig in sigs:
--> 219                     disp.compile(sig)
    220                 disp.disable_compile()
    221         return disp

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\dispatcher.py in compile(self, sig)
    963                 with ev.trigger_event("numba:compile", data=ev_details):
    964                     try:
--> 965                         cres = self._compiler.compile(args, return_type)
    966                     except errors.ForceLiteralArg as e:
    967                         def folded(args, kws):

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\dispatcher.py in compile(self, args, return_type)
    123 
    124     def compile(self, args, return_type):
--> 125         status, retval = self._compile_cached(args, return_type)
    126         if status:
    127             return retval

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\dispatcher.py in _compile_cached(self, args, return_type)
    137 
    138         try:
--> 139             retval = self._compile_core(args, return_type)
    140         except errors.TypingError as e:
    141             self._failed_cache[key] = e

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\dispatcher.py in _compile_core(self, args, return_type)
    150 
    151         impl = self._get_implementation(args, {})
--> 152         cres = compiler.compile_extra(self.targetdescr.typing_context,
    153                                       self.targetdescr.target_context,
    154                                       impl,

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
150 
    151         impl = self._get_implementation(args, {})
--> 152         cres = compiler.compile_extra(self.targetdescr.typing_context,
    153                                       self.targetdescr.target_context,
    154                                       impl,

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    714     pipeline = pipeline_class(typingctx, targetctx, library,
    715                               args, return_type, flags, locals)
--> 716     return pipeline.compile_extra(func)
    717 
    718 

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\compiler.py in compile_extra(self, func)
    450         self.state.lifted = ()
    451         self.state.lifted_from = None
--> 452         return self._compile_bytecode()
    453 
    454     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\compiler.py in _compile_bytecode(self)
    518         """
    519         assert self.state.func_ir is None
--> 520         return self._compile_core()
    521 
    522     def _compile_ir(self):

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\compiler.py in _compile_core(self)
    497                     self.state.status.fail_reason = e
    498                     if is_final_pipeline:
--> 499                         raise e
    500             else:
    501                 raise CompilerError("All available pipelines exhausted")

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\compiler.py in _compile_core(self)
    484                 res = None
    485                 try:
--> 486                     pm.run(self.state)
    487                     if self.state.cr is not None:
    488                         break

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in run(self, state)
    366                     (self.pipeline_name, pass_desc)
    367                 patched_exception = self._patch_error(msg, e)
--> 368                 raise patched_exception
    369 
    370     def dependency_analysis(self):

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in run(self, state)
    354                 pass_inst = _pass_registry.get(pss).pass_inst
    355                 if isinstance(pass_inst, CompilerPass):
--> 356                     self._runPass(idx, pass_inst, state)
    357                 else:
    358                     raise BaseException("Legacy pass in use")

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     33         def _acquire_compile_lock(*args, **kwargs):
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock
     37 
     C:\ProgramData\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in _runPass(self, index, pss, internal_state)
    309                 mutated |= check(pss.run_initialization, internal_state)
    310             with SimpleTimer() as pass_time:
--> 311                 mutated |= check(pss.run_pass, internal_state)
    312             with SimpleTimer() as finalize_time:
    313                 mutated |= check(pss.run_finalizer, internal_state)

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\compiler_machinery.py in check(func, compiler_state)
    271 
    272         def check(func, compiler_state):
--> 273             mangled = func(compiler_state)
    274             if mangled not in (True, False):
    275                 msg = ("CompilerPass implementations should return True/False. "

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\typed_passes.py in run_pass(self, state)
    392                 lower = lowering.Lower(targetctx, library, fndesc, interp,
    393                                        metadata=metadata)
--> 394                 lower.lower()
    395                 if not flags.no_cpython_wrapper:
    396                     lower.create_cpython_wrapper(flags.release_gil)

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\lowering.py in lower(self)
    166         if self.generator_info is None:
    167             self.genlower = None
--> 168             self.lower_normal_function(self.fndesc)
    169         else:
    170             self.genlower = self.GeneratorLower(self)

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_normal_function(self, fndesc)
    220         # Init argument values
    221         self.extract_function_arguments()
--> 222         entry_block_tail = self.lower_function_body()
    223 
    224         # Close tail of entry block, do not emit debug metadata else the

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_function_body(self)
249             bb = self.blkmap[offset]
    250             self.builder.position_at_end(bb)
--> 251             self.lower_block(block)
    252         self.post_lower()
    253         return entry_block_tail

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\lowering.py in lower_block(self, block)
    263             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    264                                    loc=self.loc, errcls_=defaulterrcls):
--> 265                 self.lower_inst(inst)
    266         self.post_block(block)
    267 

C:\ProgramData\Anaconda3\lib\contextlib.py in __exit__(self, typ, value, traceback)
    135                 value = typ()
    136             try:
--> 137                 self.gen.throw(typ, value, traceback)
    138             except StopIteration as exc:
    139                 # Suppress StopIteration *unless* it's the same exception that

C:\ProgramData\Anaconda3\lib\site-packages\numba\core\errors.py in new_error_context(fmt_, *args, **kwargs)
    835             else:
    836                 tb = None
--> 837             raise newerr.with_traceback(tb)
    838         elif use_new_style_errors():
    839             raise e
