### ISSUE TITLE
pl.rank_genes_groups_[heatmap|dotplot|matrixplot|stacked_violin] don't work with gene_symbol in the same way as pl.rank_genes_groups

### ISSUE THREAD

**Issue by pcm32** [scverse/scanpy#1796]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy as sc
import pandas as pd
import numpy as np
import urllib.request
   
url = "https://humancellatlas.usegalaxy.eu/datasets/11ac94870d0bb33a8d1d2e6bc37a120e/display?to_ext=h5ad"
# 75 MB anndata
urllib.request.urlretrieve(url, '11ac94.h5ad')

adata = sc.read('11ac94.h5ad')

sc.settings.figdir = '.'

sc.pl.rank_genes_groups_dotplot(
    adata,
    save='.png',
    show=False,
    gene_symbols='Symbol',
    n_genes=10,
    log=False,
    use_raw=False,
    )
```

```pytb
Traceback (most recent call last):
  File "/private/var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpenni0vju/job_working_directory/000/11/configs/tmp4tnm4xxb", line 15, in <module>
    sc.pl.rank_genes_groups_dotplot(
  File "/usr/local/lib/python3.8/site-packages/scanpy/plotting/_tools/__init__.py", line 647, in rank_genes_groups_dotplot
    return _rank_genes_groups_plot(
  File "/usr/local/lib/python3.8/site-packages/scanpy/plotting/_tools/__init__.py", line 426, in _rank_genes_groups_plot
    _pl = dotplot(
  File "/usr/local/lib/python3.8/site-packages/scanpy/plotting/_dotplot.py", line 913, in dotplot
    dp = DotPlot(
  File "/usr/local/lib/python3.8/site-packages/scanpy/plotting/_dotplot.py", line 127, in __init__
    BasePlot.__init__(
  File "/usr/local/lib/python3.8/site-packages/scanpy/plotting/_baseplot_class.py", line 105, in __init__
    self.categories, self.obs_tidy = _prepare_dataframe(
  File "/usr/local/lib/python3.8/site-packages/scanpy/plotting/_anndata.py", line 1845, in _prepare_dataframe
    obs_tidy = get.obs_df(
  File "/usr/local/lib/python3.8/site-packages/scanpy/get/get.py", line 272, in obs_df
    obs_cols, var_idx_keys, var_symbols = _check_indices(
  File "/usr/local/lib/python3.8/site-packages/scanpy/get/get.py", line 167, in _check_indices
    raise KeyError(
KeyError: "Could not find keys '['ENSMUSG00000000682', 'ENSMUSG00000000782', 'ENSMUSG00000001403', 'ENSMUSG00000002222', 'ENSMUSG00000003038', 'ENSMUSG00000004207', 'ENSMUSG00000004642', 'ENSMUSG00000005732', 'ENSMUSG00000015176', 'ENSMUSG00000016256', 'ENSMUSG00000020423', 'ENSMUSG00000020641', 'ENSMUSG00000020649', 'ENSMUSG00000020914', 'ENSMUSG00000021213', 'ENSMUSG00000022051', 'ENSMUSG00000022528', 'ENSMUSG00000023087', 'ENSMUSG00000023274', 'ENSMUSG00000023944', 'ENSMUSG00000024397', 'ENSMUSG00000025270', 'ENSMUSG00000025362', 'ENSMUSG00000025647', 'ENSMUSG00000025889', 'ENSMUSG00000025980', 'ENSMUSG00000026234', 'ENSMUSG00000026238', 'ENSMUSG00000026581', 'ENSMUSG00000026605', 'ENSMUSG00000026770', 'ENSMUSG00000027306', 'ENSMUSG00000027447', 'ENSMUSG00000027863', 'ENSMUSG00000028212', 'ENSMUSG00000028639', 'ENSMUSG00000029322', 'ENSMUSG00000029530', 'ENSMUSG00000029580', 'ENSMUSG00000029922', 'ENSMUSG00000031004', 'ENSMUSG00000031239', 'ENSMUSG00000032231', 'ENSMUSG00000034165', 'ENSMUSG00000034634', 'ENSMUSG00000036371', 'ENSMUSG00000038642', 'ENSMUSG00000038871', 'ENSMUSG00000038943', 'ENSMUSG00000039221', 'ENSMUSG00000040274', 'ENSMUSG00000044533', 'ENSMUSG00000045328', 'ENSMUSG00000046364', 'ENSMUSG00000049775', 'ENSMUSG00000052305', 'ENSMUSG00000053044', 'ENSMUSG00000053977', 'ENSMUSG00000054717', 'ENSMUSG00000056290', 'ENSMUSG00000057113', 'ENSMUSG00000057322', 'ENSMUSG00000060802', 'ENSMUSG00000061232', 'ENSMUSG00000061311', 'ENSMUSG00000061787', 'ENSMUSG00000061983', 'ENSMUSG00000062328', 'ENSMUSG00000063316', 'ENSMUSG00000063856', 'ENSMUSG00000064351', 'ENSMUSG00000066551', 'ENSMUSG00000067288', 'ENSMUSG00000069917', 'ENSMUSG00000069919', 'ENSMUSG00000073411', 'ENSMUSG00000073421', 'ENSMUSG00000073940', 'ENSMUSG00000076498', 'ENSMUSG00000076749', 'ENSMUSG00000076752', 'ENSMUSG00000076928', 'ENSMUSG00000078812', 'ENSMUSG00000079435', 'ENSMUSG00000079523', 'ENSMUSG00000094777']' in columns of `adata.obs` or in adata.var['Symbol']."
```

The same happens with the equivalents `pl.rank_genes_groups_*` for heatmap, matrixplot and stacked violin. In contrast, with the same dataset:

```
sc.pl.rank_genes_groups(
    adata,
    save='.png',
    show=False,
    n_genes=10,
    gene_symbols='Symbol',
    fontsize=8,
    ncols=4,
    sharey=True)
``` 

works well. I suspect that this is due to the dataset not having symbols as index:

```
>>> adata.var
                                    ID          Symbol    NA.  ...  dispersions_norm      mean       std
index                                                          ...
ENSMUSG00000103922  ENSMUSG00000103922          Gm6123  False  ...         -2.190900  0.001387  0.043064
ENSMUSG00000033845  ENSMUSG00000033845          Mrpl15  False  ...         -0.469772  0.349803  0.824321
ENSMUSG00000025903  ENSMUSG00000025903          Lypla1  False  ...         -0.396586  0.136585  0.531308
ENSMUSG00000104217  ENSMUSG00000104217         Gm37988  False  ...         -1.059987  0.036154  0.246548
ENSMUSG00000033813  ENSMUSG00000033813           Tcea1  False  ...         -0.342200  0.578174  1.001880
...                                ...             ...    ...  ...               ...       ...       ...
ENSMUSG00000094915  ENSMUSG00000094915      AC168977.2  False  ...         -3.593359  0.000265  0.015330
ENSMUSG00000079808  ENSMUSG00000079808      AC168977.1  False  ...         -0.756427  0.023002  0.199670
ENSMUSG00000095041  ENSMUSG00000095041      AC149090.1  False  ...          0.816554  0.149080  0.578574
ENSMUSG00000063897  ENSMUSG00000063897  CAAA01118383.1  False  ...          0.403835  0.041207  0.304460
ENSMUSG00000095742  ENSMUSG00000095742  CAAA01147332.1  False  ...         -0.307310  0.001870  0.058347
```

So when `pl.rank_genes_groups` is being called, some adequate mapping is being done from the index of `adata.var` to Symbol, whereas when the other methods are called, this mapping is skipped, hence the error. I would expect the different `pl.rank_genes_groups_*` methods to behave as `pl.rank_genes_groups` when it comes to symbols not being used as indexes.

Thanks!

#### Versions

<details>

>>> sc.logging.print_versions()
WARNING: If you miss a compact list, please try `print_header`!
-----
anndata     0.7.5
scanpy      1.7.2
sinfo       0.3.1
-----
PIL                 8.1.2
anndata             0.7.5
cairo               1.20.0
cffi                1.14.5
colorama            0.4.4
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
get_version         2.1
h5py                2.10.0
igraph              0.8.3
joblib              1.0.1
kiwisolver          1.3.1
legacy_api_wrap     0.0.0
leidenalg           0.8.3
llvmlite            0.36.0
louvain             0.7.0
matplotlib          3.3.4
mpl_toolkits        NA
natsort             7.1.1
numba               0.53.1
numexpr             2.7.3
numpy               1.19.5
packaging           20.9
pandas              1.1.5
pkg_resources       NA
pyparsing           2.4.7
pytz                2021.1
scanpy              1.7.2
scipy               1.5.3
setuptools_scm      NA
sinfo               0.3.1
six                 1.15.0
sklearn             0.24.1
sphinxcontrib       NA
tables              3.6.1
texttable           1.6.3
typing_extensions   NA
zipp                NA
-----
Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) [GCC 9.3.0]
Linux-4.19.121-linuxkit-x86_64-with-debian-10.8
2 logical CPU cores
-----
Session information updated at 2021-04-12 15:14

</details>

**Comment by ivirshup** [comment]
Thanks for the bug report, I can reproduce locally. I believe this should be fixed by: #1529.
