### ISSUE TITLE
data types preventing sc.tl.rank_genes_groups from running

### ISSUE THREAD

**Issue by alexcwsmith** [scverse/scanpy#1971]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

Since updating to scanpy 1.8 and pandas 1.3 I am getting an error with sc.tl.rank_genes_groups that my reference needs to be one of groupby=[cats], but as you can see in the traceback below, it appears identical. It has something to do with the data types, I've been dealing with this for a few weeks now and on some data sets I am eventually able to figure it out and get it to run, on some I am not.

I think this is more of a pandas issue than scanpy, so I am wondering what version of pandas you recommend for anndata 0.7.6? Or if you know a simple workaround to make sure that the datatypes match? This has been a massive headache.  I use this list(zip()) syntax in my code frequently, have never had an issue with datatypes inside of a zipped object... so this may be a simple pythonic question, but if there is a different method of accomplishing the same thing thing that doesn't introduce this error I would be happy to hear that as well.

In the example below, in my adata.obs I have a column 'condition' that is a categorical variable of biological condition for differential expression, and so all cells belong to either group 0 or 1. I have tried seemingly every combination of having these, and the leiden clusters column be integers, strings, objects, before converting to the categorical dtype in line 7 below, always get the same error, and the reference = item always appears identical to the first item in the groupby = list.

### Minimal code sample (that we can copy&paste without having any data)

```python
cluster_method='leiden'
n_genes=1000
g1n='Control'
adata.obs['condition']=adata.obs['condition'].astype('category')
adata.obs[cluster_method]=adata.obs[cluster_method].astype('category')
pairs = list(zip(adata.obs['condition'], adata.obs[cluster_method]))
adata.obs['pairs_'+cluster_method]=pairs
adata.obs['pairs_'+cluster_method]=adata.obs['pairs_'+cluster_method].astype('category')
pairs_set = list(set(pairs))
s = sorted(pairs_set)
half = int((len(s)/2))
list1 = s[:half]
list2 = s[half:]
lz_cluster_method = list(zip(list1, list2))

cat = pd.DataFrame()
for i in lz_cluster_method:
    sc.tl.rank_genes_groups(adata, 'pairs_'+cluster_method, groups=[str([i[1]])], reference=str(i[0]), use_raw=True, n_genes=n_genes, method=method)
    result = adata.uns['rank_genes_groups']
    groups = result['names'].dtype.names
    pval_table = pd.DataFrame(
            {group + '_' + key[:1]: result[key][group]
            for group in groups for key in ['names', 'pvals_adj']}).head(n_genes)
    cat = pd.concat([cat, pval_table], axis=1)
cat.to_excel(os.path.join(BaseDirectory, 'DiffExp_Upregulated_' + g1n + '_' + method + '_' + cluster_method + '_' + str(n_genes) + 'genes_rawData_adjP.xlsx'))
```

```pytb
Traceback (most recent call last):

  File "/tmp/ipykernel_40769/1343034691.py", line 3, in <module>
    sc.tl.rank_genes_groups(adata, 'pairs_'+cluster_method, groups=[str([i[1]])], reference=str(i[0]), use_raw=True, n_genes=n_genes, method=method)

  File "/home/smith/anaconda3/envs/scanpy18/lib/python3.9/site-packages/scanpy/tools/_rank_genes_groups.py", line 574, in rank_genes_groups
    raise ValueError(

ValueError: reference = (0, 0) needs to be one of groupby = [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (0, 12), (0, 14), (0, 15), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (1, 12), (1, 13), (1, 14), (1, 15)].
```

#### Versions

<details>

WARNING: If you miss a compact list, please try `print_header`!
-----
anndata     0.7.6
scanpy      1.8.1
sinfo       0.3.1
-----
2f7ece400a652629565c523b34ee61b04afa385c    NA
ACWS_filterCells                            NA
PIL                                         8.3.1
PyQt5                                       NA
absl                                        NA
anndata                                     0.7.6
appdirs                                     1.4.4
astunparse                                  1.6.3
autoreload                                  NA
backcall                                    0.2.0
beta_ufunc                                  NA
binom_ufunc                                 NA
brotli                                      NA
bs4                                         4.9.3
certifi                                     2021.05.30
cffi                                        1.14.6
chardet                                     4.0.0
charset_normalizer                          2.0.0
cloudpickle                                 1.6.0
colorama                                    0.4.4
concurrent                                  NA
cycler                                      0.10.0
cython_runtime                              NA
cytoolz                                     0.11.0
dask                                        2021.07.0
dateutil                                    2.8.2
decorator                                   5.0.9
defusedxml                                  0.7.1
encodings                                   NA
et_xmlfile                                  1.0.1
flatbuffers                                 NA
fsspec                                      2021.07.0
gast                                        NA
genericpath                                 NA
google                                      NA
gprofiler                                   1.0.0
h5py                                        3.3.0
idna                                        3.1
igraph                                      0.9.6
imagecodecs                                 2021.6.8
imageio                                     2.9.0
ipykernel                                   6.0.3
ipython_genutils                            0.2.0
jedi                                        0.17.2
joblib                                      1.0.1
keras_preprocessing                         1.1.2
kiwisolver                                  1.3.1
leidenalg                                   0.8.7
llvmlite                                    0.36.0
louvain                                     0.7.0
matplotlib                                  3.4.2
matplotlib_inline                           NA
mpl_toolkits                                NA
natsort                                     7.1.1
nbinom_ufunc                                NA
networkx                                    2.5
ntpath                                      NA
numba                                       0.53.1
numexpr                                     2.7.3
numpy                                       1.21.1
opcode                                      NA
openpyxl                                    3.0.7
opt_einsum                                  v3.3.0
packaging                                   21.0
pandas                                      1.3.0
parso                                       0.7.0
pexpect                                     4.8.0
pickleshare                                 0.7.5
pkg_resources                               NA
pooch                                       v1.4.0
posixpath                                   NA
prompt_toolkit                              3.0.19
psutil                                      5.8.0
ptyprocess                                  0.7.0
pycparser                                   2.20
pydoc_data                                  NA
pyexpat                                     NA
pygments                                    2.9.0
pynndescent                                 0.5.4
pyparsing                                   2.4.7
pytz                                        2021.1
requests                                    2.26.0
scanpy                                      1.8.1
scipy                                       1.7.0
seaborn                                     0.11.1
sinfo                                       0.3.1
sip                                         NA
six                                         1.16.0
skimage                                     0.18.2
sklearn                                     0.24.2
socks                                       1.7.1
soupsieve                                   2.0.1
sphinxcontrib                               NA
spyder                                      5.0.5
spyder_kernels                              2.0.5
spydercustomize                             NA
sre_compile                                 NA
sre_constants                               NA
sre_parse                                   NA
statsmodels                                 0.12.2
storemagic                                  NA
tables                                      3.6.1
tensorboard                                 2.5.0
tensorflow                                  2.5.0
termcolor                                   1.1.0
texttable                                   1.6.4
tifffile                                    2021.7.2
tlz                                         0.11.0
toolz                                       0.11.1
tornado                                     6.1
tqdm                                        4.61.2
traitlets                                   5.0.5
typing_extensions                           NA
umap                                        0.5.1
urllib3                                     1.26.6
wcwidth                                     0.2.5
wrapt                                       1.12.1
wurlitzer                                   2.1.0
xlsxwriter                                  1.4.4
yaml                                        5.4.1
zmq                                         22.1.0
-----
IPython             7.25.0
jupyter_client      6.1.12
jupyter_core        4.7.1
-----
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48) [GCC 9.3.0]
Linux-5.4.0-72-generic-x86_64-with-glibc2.27
40 logical CPU cores, x86_64
-----
Session information updated at 2021-07-29 21:02
</details>

PS - As a side note, another issue that pandas 1.3 introduced is that adata.write() no longer works unless I manually convert every column in adata.obs back to its original data type (e.g. adata.obs['leiden']=adata.obs['leiden'].astype('int')), because I get a TypeError from h5py until I do that.

**Comment by Zethson** [comment]
I'm going to close this for now as it mentions ancient versions of Pandas that we're absolutely not supporting anymore. Please report back if you still run into issues with the latest versions.
