### ISSUE TITLE
bbknn  integrates multiple variables

### ISSUE THREAD

**Issue by woshiyangsi** [scverse/scanpy#2004]
Dear author,

    Can bbknn integrate multiple variables？such as Platform and Individual.

Looking forward your reply
Siyu

>>> sc.external.pp.bbknn(mydata, batch_key=["Platform","Individual_2"],n_pcs=50,set_op_mix_ratio=ratio)

computing batch balanced neighbors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scCell2/miniconda3/lib/python3.8/site-packages/scanpy/external/pp/_bbknn.py", line 134, in bbknn
    return bbknn(
  File "/home/scCell2/miniconda3/lib/python3.8/site-packages/bbknn/__init__.py", line 110, in bbknn
    if batch_key not in adata.obs:
  File "/home/scCell2/miniconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 1721, in __contains__
    return key in self._info_axis
  File "/home/scCell2/miniconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4071, in __contains__
    hash(key)
TypeError: unhashable type: 'list

**Comment by f6v** [comment]
Not an author, but I don't think that's supported. You can look at the `bnknn` [docs](https://bbknn.readthedocs.io/en/latest/). I'm also interested in defining a complex batch structure. How would you imagine these two keys to interact with each other in the context of the `bknn`?
