### ISSUE TITLE
numpy.core._exceptions.MemoryError: Unable to allocate 15.9 GiB for an array with shape (180000, 23752) and data type float32

### ISSUE THREAD

**Issue by bitcometz** [scverse/scanpy#2080]
- [X] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

I used scanpy1.7 to merge different datasets, but I got the following erros.
However, I successfully used Seurat3 to merge the same datasets on the same machine.
In my opinion, scanpy saves more memory than seurat

### Minimal code sample (that we can copy&paste without having any data)

```python
df = pd.read_csv(expfile[i], sep="\t" ,index_col=0)
geneinfo = pd.DataFrame(df.index,index=df.index,columns=['gene_index'])
cellinfo = pd.DataFrame(df.columns,index=df.columns,columns=['cell_index'])
adata_tmp = sc.AnnData(df.T, obs=cellinfo, var = geneinfo)
sc.pp.filter_cells(adata_tmp, min_genes=mingenes)
sc.pp.filter_cells(adata_tmp, min_counts=minUMIs)

if maxgenes <= 1:
    maxgenes_new = np.percentile(adata_tmp.obs['n_genes'], 100*maxgenes)+1
else:
    maxgenes_new = maxgenes
if maxUMIs <= 1:
    maxUMIs_new = np.percentile(adata_tmp.obs['n_counts'], 100*maxUMIs)+1
else:
    maxUMIs_new = maxUMIs
sc.pp.filter_cells(adata_tmp, max_genes=maxgenes_new)
sc.pp.filter_cells(adata_tmp, max_counts=maxUMIs_new)
sc.pp.filter_genes(adata_tmp, min_cells=mincells)
adata_tmp.obs['sample'] = ugname[i]
adata = sc.concat([adata,adata_tmp],join='outer')
```

```pytb
filtered out 5508 genes that are detected in less than 5 cells
filtered out 5905 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 6390 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 5974 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 7136 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 5971 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 6234 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 6442 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 5593 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 6412 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 6662 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 6039 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 6036 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 5923 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 6767 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 7077 genes that are detected in less than 5 cells
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
filtered out 6080 genes that are detected in less than 5 cells
Traceback (most recent call last):
  File "/mypath/runMulti_scanpy.py", line 161, in main
    adata = sc.concat([adata,adata_tmp],join='outer')
  File "/mypath/scanpy1.7/lib/python3.8/site-packages/anndata/_core/merge.py", line 818, in concat
    X = concat_arrays(
  File "/mypath/scanpy1.7/lib/python3.8/site-packages/anndata/_core/merge.py", line 424, in concat_arrays
    return np.concatenate(
  File "<__array_function__ internals>", line 5, in concatenate
numpy.core._exceptions.MemoryError: Unable to allocate 15.9 GiB for an array with shape (180000, 23752) and data type float32
```

Thanks  !!!

**Comment by chris-rands** [comment]
can you use `join='inner'` instead?

**Comment by ivirshup** [comment]
I would also consider whether you expression is sparse, or if the values have been densified

**Comment by eroell** [comment]
As we haven't heard back after the follow-up we will close the issue for now, hopefully you obtained the expected behaviour in the end :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)

**Comment by malonzm1** [comment]
Hi @bitcometz 

Were you able to resolve this problem? I have a similar problem.. Am wondering if you have a solution. Thanks.
