### ISSUE TITLE
[Docker Image] scanpy  Installation

### ISSUE THREAD

**Issue by AMA111** [scverse/scanpy#2113]
Hey, 

I am trying to install scanpy through a Docker image. I get stuck in importing  scanpy; It seems that the error has some link to numba but I am not sure!
 
### Minimal code sample:

```python
python -c "from numba.caching import _UserProvidedCacheLocator; print(_UserProvidedCacheLocator(lambda x:x, 'string').get_cache_path())"
python -c "import numba;print(numba.__version__)"
python -c "import anndata;print(anndata.__version__)"
python -c "import torch;print(torch.__version__)"
python -c "import librosa;print(librosa.__version__)"
python -c "import torch;print(torch.__version__)"
python -c "import scanpy;print(scanpy.__version__)"
```

###  errors:

```python
/workspace
/opt/conda/bin/python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numba.caching'
0.53.1
0.7.8
1.10.1+cu102
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/opt/conda/lib/python3.7/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/opt/conda/lib/python3.7/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/opt/conda/lib/python3.7/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/opt/conda/lib/python3.7/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/opt/conda/lib/python3.7/site-packages/librosa/util/utils.py", line 1848, in <module>
    def __shear_dense(X, factor=+1, axis=-1):
  File "/opt/conda/lib/python3.7/site-packages/numba/core/decorators.py", line 214, in wrapper
    disp.enable_caching()
  File "/opt/conda/lib/python3.7/site-packages/numba/core/dispatcher.py", line 812, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/opt/conda/lib/python3.7/site-packages/numba/core/caching.py", line 610, in __init__
    self._impl = self._impl_class(py_func)
  File "/opt/conda/lib/python3.7/site-packages/numba/core/caching.py", line 348, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function '__shear_dense': no locator available for file '/opt/conda/lib/python3.7/site-packages/librosa/util/utils.py'
1.10.1+cu102
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/scanpy/__init__.py", line 14, in <module>
    from . import tools as tl
  File "/opt/conda/lib/python3.7/site-packages/scanpy/tools/__init__.py", line 1, in <module>
    from ..preprocessing import pca
  File "/opt/conda/lib/python3.7/site-packages/scanpy/preprocessing/__init__.py", line 1, in <module>
    from ._recipes import recipe_zheng17, recipe_weinreb17, recipe_seurat
  File "/opt/conda/lib/python3.7/site-packages/scanpy/preprocessing/_recipes.py", line 7, in <module>
    from ._deprecated.highly_variable_genes import (
  File "/opt/conda/lib/python3.7/site-packages/scanpy/preprocessing/_deprecated/highly_variable_genes.py", line 11, in <module>
    from .._utils import _get_mean_var
  File "/opt/conda/lib/python3.7/site-packages/scanpy/preprocessing/_utils.py", line 45, in <module>
    @numba.njit(cache=True)
  File "/opt/conda/lib/python3.7/site-packages/numba/core/decorators.py", line 214, in wrapper
    disp.enable_caching()
  File "/opt/conda/lib/python3.7/site-packages/numba/core/dispatcher.py", line 812, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/opt/conda/lib/python3.7/site-packages/numba/core/caching.py", line 610, in __init__
    self._impl = self._impl_class(py_func)
  File "/opt/conda/lib/python3.7/site-packages/numba/core/caching.py", line 348, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function 'sparse_mean_var_minor_axis': no locator available for file '/opt/conda/lib/python3.7/site-packages/scanpy/preprocessing/_utils.py'

```

I would highly appreciate if you could please point out how to fix this issue. 

Thank you in advance!

Best wishes,
Abdelrahman 

```

#### Versions

<details>

numba==0.53.1
scanpy==1.8.1

</details>

**Comment by AMA111** [comment]
### Found a solution:  Just add the following at the start of your python script

##
``` python
import os
os.environ[ 'NUMBA_CACHE_DIR' ] = '/tmp/'

```

I closed this issue 👍 

Best, Abdelrahman
