### ISSUE TITLE
ImportError: cannot import name 'sparsefuncs'

### ISSUE THREAD

**Issue by grimwoo** [scverse/scanpy#2165]
Hi, thanks for developing Scanpy. Here, I encountered the error, `ImportError: cannot import name 'sparsefuncs'`. To solve this problem, I re-installed "sklearn.utils" and "sklearn". However, I still get this error when importing Scanpy.

The Scanpy runs correctly in my linux system, but it cannot be imported corrected in my windows 10 system.

**Here is the code and error information:**

`>>> import sklearn.utils`
`>>> import sklearn`
`>>> import scanpy`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\system_software\Miniconda3\envs\PAGA\lib\site-packages\scanpy\__init__.py", line 15, in <module>
    from . import tools as tl
  File "D:\system_software\Miniconda3\envs\PAGA\lib\site-packages\scanpy\tools\__init__.py", line 1, in <module>
    from ..preprocessing import pca
  File "D:\system_software\Miniconda3\envs\PAGA\lib\site-packages\scanpy\preprocessing\__init__.py", line 1, in <module>
    from ._recipes import recipe_zheng17, recipe_weinreb17, recipe_seurat
  File "D:\system_software\Miniconda3\envs\PAGA\lib\site-packages\scanpy\preprocessing\_recipes.py", line 11, in <module>
    from ._normalization import normalize_total
  File "D:\system_software\Miniconda3\envs\PAGA\lib\site-packages\scanpy\preprocessing\_normalization.py", line 6, in <module>
    from sklearn.utils import sparsefuncs
ImportError: cannot import name 'sparsefuncs'

**Comment by grimwoo** [comment]
This error is certainly caused by "scikit-learn".

I abandoned this conda environment and created a new one by `conda create -n Scanpy -c conda-forge scikit-learn`[https://scikit-learn.org/stable/install.html](url).
