### ISSUE TITLE
Cannot import Scanpy

### ISSUE THREAD

**Issue by charles-xu-ru** [scverse/scanpy#2173]
```python
import scanpy as sc
```

```pytb
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_22924/912249142.py in <module>
----> 1 import scanpy as sc

~\Anaconda3\lib\site-packages\scanpy\__init__.py in <module>
     13     Verbosity,
     14 )  # start with settings as several tools are using it
---> 15 from . import tools as tl
     16 from . import preprocessing as pp
     17 from . import plotting as pl

~\Anaconda3\lib\site-packages\scanpy\tools\__init__.py in <module>
     15 from ._leiden import leiden
     16 from ._louvain import louvain
---> 17 from ._sim import sim
     18 from ._score_genes import score_genes, score_genes_cell_cycle
     19 from ._dendrogram import dendrogram

~\Anaconda3\lib\site-packages\scanpy\tools\_sim.py in <module>
     21 from anndata import AnnData
     22 
---> 23 from .. import _utils, readwrite, logging as logg
     24 from .._settings import settings
     25 from .._compat import Literal

~\Anaconda3\lib\site-packages\scanpy\readwrite.py in <module>
      8 import pandas as pd
      9 from matplotlib.image import imread
---> 10 import tables
     11 import anndata
     12 from anndata import (

~\Anaconda3\lib\site-packages\tables\__init__.py in <module>
     40 # Import the user classes from the proper modules
     41 from .exceptions import *
---> 42 from .file import File, open_file, copy_file
     43 from .node import Node
     44 from .group import Group

~\Anaconda3\lib\site-packages\tables\file.py in <module>
     21 import numpy as np
     22 
---> 23 from . import hdf5extension
     24 from . import utilsextension
     25 from . import parameters

ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by charles-xu-ru** [comment]
I used windows 64 and anaconda. Scanpy has been working and I never had this issue before in the last two years.

**Comment by Zethson** [comment]
How did you install scanpy? What conda command did you use?

**Comment by Zethson** [comment]
Ah, duplicate of https://github.com/theislab/scanpy/issues/1468
Next time please kindly look for the issue in the existing issues. There's a reason why we are kindly asking you to tick the boxes in the issue template :)

**Comment by charles-xu-ru** [comment]
I checked #1468. Tried conda install pytables. But it did not work.

**Comment by Zethson** [comment]
Did you look at https://github.com/theislab/scanpy/issues/454 ?

**Comment by Zethson** [comment]
> How did you install scanpy? What conda command did you use?

And I'd appreciate an answer here. Just want to rule out that you used bioconda.

**Comment by charles-xu-ru** [comment]
conda install pytables

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

But there is still ImportError.

**Comment by charles-xu-ru** [comment]
<details>
<summary>Installed scanpy on jupyter notebook/ anaconda: </summary>

```
pip install scanpy

Requirement already satisfied: scanpy in c:\users\charles\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numba>=0.41.0 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (0.44.1)
Requirement already satisfied: tables in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (3.7.0)
Requirement already satisfied: anndata>=0.7.4 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (0.7.6)
Requirement already satisfied: legacy-api-wrap in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (1.2)
Requirement already satisfied: packaging in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (21.3)
Requirement already satisfied: pandas>=0.21 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (1.3.4)
Requirement already satisfied: scipy>=1.4 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (1.7.3)
Requirement already satisfied: umap-learn>=0.3.10 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (0.5.1)
Requirement already satisfied: h5py>=2.10.0 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (2.10.0)
Requirement already satisfied: scikit-learn>=0.21.2 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (1.0.2)
Requirement already satisfied: statsmodels>=0.10.0rc2 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (0.13.0)
Requirement already satisfied: matplotlib>=3.1.2 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (3.5.1)
Requirement already satisfied: numpy>=1.17.0 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (1.21.5)
Requirement already satisfied: seaborn in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (0.11.2)
Requirement already satisfied: tqdm in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (4.62.3)
Requirement already satisfied: natsort in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (7.1.1)
Requirement already satisfied: networkx>=2.3 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (2.6.3)
Requirement already satisfied: importlib-metadata>=0.7 in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (4.8.2)
Requirement already satisfied: joblib in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (1.1.0)
Requirement already satisfied: sinfo in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (0.3.4)
Requirement already satisfied: patsy in c:\users\charles\anaconda3\lib\site-packages (from scanpy) (0.5.2)
Collecting xlrd<2.0
  Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Requirement already satisfied: six in c:\users\charles\anaconda3\lib\site-packages (from h5py>=2.10.0->scanpy) (1.16.0)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\users\charles\anaconda3\lib\site-packages (from importlib-metadata>=0.7->scanpy) (3.10.0.2)
Requirement already satisfied: zipp>=0.5 in c:\users\charles\anaconda3\lib\site-packages (from importlib-metadata>=0.7->scanpy) (3.7.0)
Requirement already satisfied: cycler>=0.10 in c:\users\charles\anaconda3\lib\site-packages (from matplotlib>=3.1.2->scanpy) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\charles\anaconda3\lib\site-packages (from matplotlib>=3.1.2->scanpy) (3.0.4)
Requirement already satisfied: pillow>=6.2.0 in c:\users\charles\anaconda3\lib\site-packages (from matplotlib>=3.1.2->scanpy) (9.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\charles\anaconda3\lib\site-packages (from matplotlib>=3.1.2->scanpy) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\charles\anaconda3\lib\site-packages (from matplotlib>=3.1.2->scanpy) (4.25.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\charles\anaconda3\lib\site-packages (from matplotlib>=3.1.2->scanpy) (2.8.2)
Requirement already satisfied: llvmlite>=0.29.0 in c:\users\charles\anaconda3\lib\site-packages (from numba>=0.41.0->scanpy) (0.29.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\charles\anaconda3\lib\site-packages (from pandas>=0.21->scanpy) (2021.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\charles\anaconda3\lib\site-packages (from scikit-learn>=0.21.2->scanpy) (2.2.0)
Collecting numba>=0.41.0
  Using cached numba-0.55.1-cp37-cp37m-win_amd64.whl (2.4 MB)
Requirement already satisfied: pynndescent>=0.5 in c:\users\charles\anaconda3\lib\site-packages (from umap-learn>=0.3.10->scanpy) (0.5.2)
Requirement already satisfied: setuptools in c:\users\charles\anaconda3\lib\site-packages (from numba>=0.41.0->scanpy) (58.0.4)
Collecting llvmlite>=0.29.0
  Using cached llvmlite-0.38.0-cp37-cp37m-win_amd64.whl (23.2 MB)
Requirement already satisfied: get-version>=2.0.4 in c:\users\charles\anaconda3\lib\site-packages (from legacy-api-wrap->scanpy) (2.2)
Requirement already satisfied: stdlib-list in c:\users\charles\anaconda3\lib\site-packages (from sinfo->scanpy) (0.8.0)
Requirement already satisfied: numexpr>=2.6.2 in c:\users\charles\anaconda3\lib\site-packages (from tables->scanpy) (2.8.1)
Requirement already satisfied: colorama in c:\users\charles\anaconda3\lib\site-packages (from tqdm->scanpy) (0.4.4)
Installing collected packages: llvmlite, numba, xlrd
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.29.0
Note: you may need to restart the kernel to use updated packages.
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

</details>

**Comment by charles-xu-ru** [comment]
I have been running the same scripts on the same computer (windows 10) for two years with no problem until recently.

**Comment by charles-xu-ru** [comment]
> Did you look at #454 ?

I tried to downgrade h5py but still did not work.

**Comment by Zethson** [comment]
Honestly, I don't use Windows and somebody else needs to chip in here, sorry.

**Comment by Koncopd** [comment]
@charles-xu-ru you could also try installing numba from conda before installing scanpy. pytables better to install from conda-forge channel along with h5py.

**Comment by Yiquan-Jiang** [comment]
I met the same problem. 

```pytb
>>> import scanpy.api as sc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\scanpy\__init__.py", line 14, in <module>
    from . import tools as tl
  File "C:\ProgramData\Miniconda3\lib\site-packages\scanpy\tools\__init__.py", line 1, in <module>
    from ..preprocessing import pca
  File "C:\ProgramData\Miniconda3\lib\site-packages\scanpy\preprocessing\__init__.py", line 1, in <module>
    from ._recipes import recipe_zheng17, recipe_weinreb17, recipe_seurat
  File "C:\ProgramData\Miniconda3\lib\site-packages\scanpy\preprocessing\_recipes.py", line 11, in <module>
    from ._normalization import normalize_total
  File "C:\ProgramData\Miniconda3\lib\site-packages\scanpy\preprocessing\_normalization.py", line 7, in <module>
    from sklearn.utils import sparsefuncs
  File "C:\ProgramData\Miniconda3\lib\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "C:\ProgramData\Miniconda3\lib\site-packages\sklearn\base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "C:\ProgramData\Miniconda3\lib\site-packages\sklearn\utils\__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "C:\ProgramData\Miniconda3\lib\site-packages\sklearn\utils\fixes.py", line 20, in <module>
    import scipy.stats
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\stats\__init__.py", line 441, in <module>
    from .stats import *
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\stats\stats.py", line 43, in <module>
    from . import distributions
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\stats\distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\optimize\__init__.py", line 400, in <module>
    from .optimize import *
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\optimize\optimize.py", line 36, in <module>
    from ._numdiff import approx_derivative
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\optimize\_numdiff.py", line 6, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .eigen import *
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 9, in <module>
    from .arpack import *
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 20, in <module>
    from .arpack import *
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 42, in <module>
    from . import _arpack
ImportError: DLL load failed while importing _arpack: The specified procedure could not be found.
```

**Comment by Zethson** [comment]
Are you two running Windows 10 or 11?

@Yiquan-Jiang could you please also provide the full information? OS, environment etc

**Comment by Zethson** [comment]
Closing due to lack of information. Feel free to reopen.

**Comment by IfSumia** [comment]
Hello, I get the same error when importing scanpy on 7bridges.

```pytb
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_109/912249142.py in <module>
----> 1 import scanpy as sc

/opt/conda/lib/python3.9/site-packages/scanpy/__init__.py in <module>
     14     from . import tools as tl
     15     from . import preprocessing as pp
---> 16     from . import plotting as pl
     17     from . import datasets, logging, queries, external, get, metrics, experimental
     18 

/opt/conda/lib/python3.9/site-packages/scanpy/plotting/__init__.py in <module>
     14 from ._preprocessing import filter_genes_dispersion, highly_variable_genes
     15 
---> 16 from ._tools.scatterplots import (
     17     embedding,
     18     pca,

/opt/conda/lib/python3.9/site-packages/scanpy/plotting/_tools/__init__.py in <module>
      8 from matplotlib.colors import Normalize
      9 from matplotlib import pyplot as pl
---> 10 from matplotlib import rcParams, colormaps
     11 from anndata import AnnData
     12 from typing import Union, Optional, List, Sequence, Iterable, Mapping, Literal

ImportError: cannot import name 'colormaps' from 'matplotlib' (/opt/conda/lib/python3.9/site-packages/matplotlib/__init__.py)
```

**Comment by flying-sheep** [comment]
Hi @IfSumia, that’s a very different problem, see the last line:

```pytb
ImportError: cannot import name 'colormaps' from 'matplotlib' (/opt/conda/lib/python3.9/site-packages/matplotlib/__init__.py)
```

This probably means that you should update matplotlib and try again
