### ISSUE TITLE
AttributeError: module 'fa2.fa2util' has no attribute 'Node' for version 1.9.1

### ISSUE THREAD

**Issue by wubaosheng** [scverse/scanpy#2286]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---
AttributeError: module 'fa2.fa2util' has no attribute 'Node' for scanpy version 1.9.1

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
adata = sc.datasets.paul15()
sc.pp.recipe_zheng17(adata)
sc.tl.pca(adata, svd_solver='arpack')
sc.pp.neighbors(adata, n_neighbors=4, n_pcs=20)
sc.tl.draw_graph(adata)
```

```pytb
Traceback (most recent call last):
  File "C:\Users\wubaosheng\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-e2440b0eca68>", line 1, in <cell line: 1>
    sc.tl.draw_graph(adata)
  File "C:\Users\wubaosheng\AppData\Local\Programs\Python\Python39\lib\site-packages\scanpy\tools\_draw_graph.py", line 159, in draw_graph
    positions = forceatlas2.forceatlas2(
  File "C:\Users\wubaosheng\AppData\Local\Programs\Python\Python39\lib\site-packages\fa2-0.3.5-py3.9-win-amd64.egg\fa2\forceatlas2.py", line 162, in forceatlas2
    nodes, edges = self.init(G, pos)
  File "C:\Users\wubaosheng\AppData\Local\Programs\Python\Python39\lib\site-packages\fa2-0.3.5-py3.9-win-amd64.egg\fa2\forceatlas2.py", line 103, in init
    n = fa2util.Node()
AttributeError: module 'fa2.fa2util' has no attribute 'Node'
```

#### Versions
'1.9.1' for scanpy
3.9.7 for python

![image](https://user-images.githubusercontent.com/50618480/176398309-d16c671f-e4bf-43b5-a23d-abf9bdbe2329.png)

**Comment by tangguangjue** [comment]
hi,I wonder if this problem has been solved? This error also occurred recently when I used this code

**Comment by CZHanoi** [comment]
hi,I wonder if this problem has been solved? This error also occurred recently when I used this code, too.

**Comment by flying-sheep** [comment]
Please go here for help with your problem https://github.com/bhargavchippada/forceatlas2/issues/32

We can‘t help you here, as we aren’t the `forceatlas2` developers
