### ISSUE TITLE
highly_variable_genes: layer does not work together with batch_key

### ISSUE THREAD

**Issue by DriesSchaumont** [scverse/scanpy#2396]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy as sc
pbmc = sc.datasets.pbmc3k()
log_anndata = sc.pp.log1p(pbmc, copy=True)
pbmc.layers['log_transformed'] = log_anndata.X.copy()

# This errors, because X is not normalized and flavor="seurat" requires normalizes data.
# ValueError: cannot specify integer `bins` when input data contains infinity
sc.pp.highly_variable_genes(pbmc, flavor="seurat", subset=False, inplace=False)

# This works, we pass log tranformed data
pbmc.uns['log1p'] = log_anndata.uns['log1p']
sc.pp.highly_variable_genes(pbmc, layer="log_transformed", flavor="seurat", subset=False, inplace=False)

# This raises ValueError again
pbmc.obs['batch'] = 'A'
column_index = pbmc.obs.columns.get_indexer(['batch'])
pbmc.obs.iloc[slice(pbmc.n_obs//2, None), column_index] = 'B'
sc.pp.highly_variable_genes(pbmc, layer="log_transformed", flavor="seurat", subset=False, inplace=False, batch_key="batch")
```

```pytb
>>> import scanpy as sc
g_anndata = sc.pp.log1p(pbmc, copy=True)
pbmc.layers['log_transformed'] = log_anndata.X.copy()

# This errors, because X is not normalized and flavor="seurat" requires normalizes data.
# ValueError: cannot specify integer `bins` when input data contains infinity
sc.pp.highly_variable_genes(pbmc, flavor="seurat", subset=False, inplace=False)

# This works, we pass log tranformed data
pbmc.uns['log1p'] = log_anndata.uns['log1p']
sc.pp.highly_variable_genes(pbmc, layer="log_transformed", flavor="seurat", subset=False, inplace=False)

# This raises ValueError again
pbmc.obs['batch'] = 'A'
column_index = pbmc.obs.columns.get_indexer(['batch'])
pbmc.obs.iloc[slice(pbmc.n_obs//2, None), column_index] = 'B'
sc.pp.highly_variable_genes(pbmc, layer="log_transformed", flavor="seurat", subset=False, inplace=False, batch_key="batch")>>> pbmc = sc.datasets.pbmc3k()

>>> log_anndata = sc.pp.log1p(pbmc, copy=True)
>>> pbmc.layers['log_transformed'] = log_anndata.X.copy()
>>> 
>>> # This errors, because X is not normalized and flavor="seurat" requires normalizes data.
>>> # ValueError: cannot specify integer `bins` when input data contains infinity
>>> sc.pp.highly_variable_genes(pbmc, flavor="seurat", subset=False, inplace=False)
.venv/lib/python3.10/site-packages/scipy/sparse/_data.py:133: RuntimeWarning: overflow encountered in expm1
  result = op(self._deduped_data())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 434, in highly_variable_genes
    df = _highly_variable_genes_single_batch(
  File ".venv/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 215, in _highly_variable_genes_single_batch
    df['mean_bin'] = pd.cut(df['means'], bins=n_bins)
  File ".venv/lib/python3.10/site-packages/pandas/core/reshape/tile.py", line 263, in cut
    raise ValueError(
ValueError: cannot specify integer `bins` when input data contains infinity
>>> 
>>> # This works, we pass log tranformed data
>>> pbmc.uns['log1p'] = log_anndata.uns['log1p']
>>> sc.pp.highly_variable_genes(pbmc, layer="log_transformed", flavor="seurat", subset=False, inplace=False)
              means  dispersions           mean_bin  dispersions_norm  highly_variable
0      1.000000e-12          NaN  (-0.00411, 0.205]               0.0            False
1      1.000000e-12          NaN  (-0.00411, 0.205]               0.0            False
2      1.000000e-12          NaN  (-0.00411, 0.205]               0.0            False
3      1.000000e-12          NaN  (-0.00411, 0.205]               0.0            False
4      1.000000e-12          NaN  (-0.00411, 0.205]               0.0            False
...             ...          ...                ...               ...              ...
32733  1.000000e-12          NaN  (-0.00411, 0.205]               0.0            False
32734  1.000000e-12          NaN  (-0.00411, 0.205]               0.0            False
32735  1.000000e-12          NaN  (-0.00411, 0.205]               0.0            False
32736  1.000000e-12          NaN  (-0.00411, 0.205]               0.0            False
32737  1.000000e-12          NaN  (-0.00411, 0.205]               0.0            False

[32738 rows x 5 columns]
>>> 
>>> # This raises ValueError again
>>> pbmc.obs['batch'] = 'A'
>>> column_index = pbmc.obs.columns.get_indexer(['batch'])
>>> pbmc.obs.iloc[slice(pbmc.n_obs//2, None), column_index] = 'B'
>>> sc.pp.highly_variable_genes(pbmc, layer="log_transformed", flavor="seurat", subset=False, inplace=False, batch_key="batch")
.venv/lib/python3.10/site-packages/scipy/sparse/_data.py:133: RuntimeWarning: overflow encountered in expm1
  result = op(self._deduped_data())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 459, in highly_variable_genes
    hvg = _highly_variable_genes_single_batch(
  File ".venv/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 215, in _highly_variable_genes_single_batch
    df['mean_bin'] = pd.cut(df['means'], bins=n_bins)
  File ".venv/lib/python3.10/site-packages/pandas/core/reshape/tile.py", line 263, in cut
    raise ValueError(
ValueError: cannot specify integer `bins` when input data contains infinity

```

#### Versions

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

-----
anndata     0.8.0
scanpy      1.9.1
-----
PIL                 9.3.0
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.2
google              NA
h5py                3.7.0
joblib              1.2.0
kiwisolver          1.4.4
llvmlite            0.39.1
matplotlib          3.6.2
mpl_toolkits        NA
natsort             8.2.0
numba               0.56.4
numpy               1.23.5
packaging           22.0
pandas              1.5.2
psutil              5.9.4
pyarrow             10.0.1
pyparsing           3.0.9
pytz                2022.7
scipy               1.9.3
session_info        1.0.0
sitecustomize       NA
six                 1.16.0
sklearn             1.2.0
threadpoolctl       3.1.0
typing_extensions   NA
yaml                6.0
zoneinfo            NA
-----
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Linux-5.15.0-57-generic-x86_64-with-glibc2.35
-----
Session information updated at 2023-01-09 18:53

</details>

**Comment by DriesSchaumont** [comment]
Seems I created a duplicate of an issue that I already solved myself 🙄 See https://github.com/scverse/scanpy/pull/2302
