### ISSUE TITLE
obs_names_make_unique not working?

### ISSUE THREAD

**Issue by Jiayi-Zheng** [scverse/scanpy#2432]
Hi, I was doing a dataset integration on quite some datasets. 

```py
adatas = [AT1,AT2,AT3,AT4,AT5,AT6,AT7] #each is an adata object from scRNA-seq

for i in adatas:
    i.layers['counts'] = i.X

adatas = [AT1,AT2,AT3,AT4,AT5,AT6,AT7]

adata = ad.concat(adatas)
adata.obs_names_make_unique

sc.pp.log1p(adata)
sc.pp.highly_variable_genes(
    adata,
    layer="logcounts",
    batch_key="Sample",
    subset=True
)

scvi.model.SCVI.setup_anndata(adata, layer="counts", batch_key="Sample")

vae = scvi.model.SCVI(adata, n_hidden=256)
vae.train()
adata.obsm["X_scVI"] = vae.get_latent_representation()
sc.pp.neighbors(adata, use_rep="X_scVI")
from scvi.model.utils import mde
import pymde
adata.obsm["X_mde"] = mde(adata.obsm["X_scVI"])
adata.obsm["X_normalized_scVI"] = vae.get_normalized_expression()
adata.write_h5ad('Integrated.h5ad')
```

So I did use make obs names unique after ad.concat(adatas). However, after I was finished with the integration and moving on to write_h5ad, it returns the following errors and tells me they can't write my h5ad cuz I have duplicated rows:

```pytb
Feb 26 11:20:39 PM: Your dataset appears to contain duplicated items (rows); when embedding, you should typically have unique items.
Feb 26 11:20:39 PM: The following items have duplicates [60449 60452 60455 ... 70783 70784 70785]
Traceback (most recent call last):
  File "/home/joyzheng/.local/lib/python3.8/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/home/joyzheng/.local/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 171, in write_elem
    _REGISTRY.get_writer(dest_type, (t, elem.dtype.kind), modifiers)(
  File "/home/joyzheng/.local/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 24, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/home/joyzheng/.local/lib/python3.8/site-packages/anndata/_io/specs/methods.py", line 346, in write_vlen_string_array
    f.create_dataset(k, data=elem.astype(str_dtype), dtype=str_dtype, **dataset_kwargs)
  File "/home/joyzheng/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/home/joyzheng/.local/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 168, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 280, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 145, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 444, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 95, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 249, in h5py._conv.conv_str2vlen
TypeError: Can't implicitly convert non-string objects to strings

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "integration.py", line 66, in <module>
    adata.write_h5ad('Integrated.h5ad')
  File "/home/joyzheng/.local/lib/python3.8/site-packages/anndata/_core/anndata.py", line 1918, in write_h5ad
    _write_h5ad(
  File "/home/joyzheng/.local/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 98, in write_h5ad
    write_elem(f, "obs", adata.obs, dataset_kwargs=dataset_kwargs)
  File "/home/joyzheng/.local/lib/python3.8/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/home/joyzheng/.local/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 175, in write_elem
    _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)
  File "/home/joyzheng/.local/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 24, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/home/joyzheng/.local/lib/python3.8/site-packages/anndata/_io/specs/methods.py", line 514, in write_dataframe
    write_elem(group, colname, series._values, dataset_kwargs=dataset_kwargs)
  File "/home/joyzheng/.local/lib/python3.8/site-packages/anndata/_io/utils.py", line 220, in func_wrapper
    raise type(e)(
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'orig.ident' of <class 'h5py._hl.group.Group'> to /
/home/joyzheng/.conda/envs/cellrank/lib/python3.8/tempfile.py:818: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpzjzxl3q5'>
  _warnings.warn(warn_message, ResourceWarning)```

**Comment by eroell** [comment]
Hi, thanks for your interest in scanpy!

Sorry for being slow here!

Would it be possible that you can add a minimal reproducible example so someone could generate adata objects (with some dummy data) in the style you are using them so we could check this?

Sidenote: from a first impression you are using `adata.obs_names_make_unique`: you might want to double check to _call_ the function here by adding `()` at the end of the line: `adata.obs_names_make_unique()`.
