### ISSUE TITLE
Cannot import scanpy due to numba issues

### ISSUE THREAD

**Issue by Yijia-Jiang** [scverse/scanpy#2438]
Hello, I am unable to import scanpy and the error message shows below:

```python
import scanpy as sc
```

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.9/site-packages/scanpy/__init__.py", line 6, in <module>
    from ._utils import check_versions
  File "/opt/anaconda3/lib/python3.9/site-packages/scanpy/_utils/__init__.py", line 29, in <module>
    from .compute.is_constant import is_constant
  File "/opt/anaconda3/lib/python3.9/site-packages/scanpy/_utils/compute/is_constant.py", line 5, in <module>
    from numba import njit
ImportError: cannot import name 'njit' from 'numba' (unknown location)```
```

Scanpy has been working well, but today it reports an issue. I have tried to uninstall and reinstall numba and scanpy, but it still did not work. Can you help? Thank you very much.

**Comment by Zethson** [comment]
Please provide more details such as your whole environment and what you've tried so far. Ensure that you can import numba on its own first before trying to import scanpy.

**Comment by Yijia-Jiang** [comment]
I uninstalled and then installed scanpy. This resolves the issue.
