### ISSUE TITLE
metaclass conflict

### ISSUE THREAD

**Issue by smilesun** [scverse/scanpy#2445]
```
Python 3.9.15 (main, Nov 24 2022, 14:31:59) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scanpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/lib/python3.9/site-packages/scanpy/__init__.py", line 16, in <module>
    from . import plotting as pl
  File "/home/user/anaconda3/lib/python3.9/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/home/user/anaconda3/lib/python3.9/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
    from . import _utils
  File "/home/user/anaconda3/lib/python3.9/site-packages/scanpy/plotting/_utils.py", line 35, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
# Your code here
```

```pytb
[Paste the error output produced by the above code here]
```

#### Versions

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>

**Comment by smilesun** [comment]
resolved via 

pip install 'matplotlib<3.7'

**Comment by ivirshup** [comment]
This is also fixed by newer releases of scanpy
