### ISSUE TITLE
Can not read  loom file 

### ISSUE THREAD

**Issue by crystal0721** [scverse/scanpy#2461]
Dears
     Thanks for this great tools. We had loom file from Seurat(V4), while got  those Error when used 'sc.read_loom'   function:

```pytb
   sc_adata=sc.read_loom(sc_input,sparse = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./miniconda/miniconda/envs/scrna/lib/python3.8/site-packages/anndata/compat/__init__.py", line 253, in inner_f
    return f(*args, **kwargs)
  File "./miniconda/miniconda/envs/scrna/lib/python3.8/site-packages/anndata/_io/read.py", line 280, in read_loom
    obs, obsm = _fmt_loom_axis_attrs(dict(lc.col_attrs), obs_names, obsm_mapping)
  File "./miniconda/miniconda/envs/scrna/lib/python3.8/site-packages/anndata/_io/read.py", line 159, in _fmt_loom_axis_attrs
    if v.ndim > 1 and v.shape[1] > 1:
AttributeError: 'NoneType' object has no attribute 'ndim'  
```

We want to know how to solve this,  we are looking forward for your help, thanks.

**Comment by eroell** [comment]
Hi,
thanks for your interest in scanpy and for raising your question!

Could you provide a minimal reproducible example of how you arrive at a loom file in the format you are trying to read here? :)
