### ISSUE TITLE
ArpackError in sc.tl.pca 

### ISSUE THREAD

**Issue by gwosd** [scverse/scanpy#2473]
I followed the tutorial on [Preprocessing and clustering 3k PBMCs](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html). The first steps worked quit well, but when I want to run PCA the following error occurs (see below).

Follow the tutorial ([pbmc3k.ipynb](https://github.com/scverse/scanpy-tutorials/blob/75c5ebb5b63769aee65f38842a34b7f7e1bbd476/pbmc3k.ipynb)) until the following line:

```python
sc.tl.pca(adata, svd_solver='arpack')
```

```pytb
Traceback (most recent call last):
  File "/Users/pbinder/Nextcloud/projects/memory-tcell-scRNA-seq/tutorials/scanpy/scanpy-tutorials-master/test.py", line 51, in <module>
    sc.tl.pca(adata, svd_solver='arpack')
  File "/Users/pbinder/opt/anaconda3/envs/scRNA/lib/python3.9/site-packages/scanpy/preprocessing/_pca.py", line 188, in pca
    X_pca = pca_.fit_transform(X)
  File "/Users/pbinder/opt/anaconda3/envs/scRNA/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/pbinder/opt/anaconda3/envs/scRNA/lib/python3.9/site-packages/sklearn/decomposition/_pca.py", line 462, in fit_transform
    U, S, Vt = self._fit(X)
  File "/Users/pbinder/opt/anaconda3/envs/scRNA/lib/python3.9/site-packages/sklearn/decomposition/_pca.py", line 514, in _fit
    return self._fit_truncated(X, n_components, self._fit_svd_solver)
  File "/Users/pbinder/opt/anaconda3/envs/scRNA/lib/python3.9/site-packages/sklearn/decomposition/_pca.py", line 609, in _fit_truncated
    U, S, Vt = svds(X, k=n_components, tol=self.tol, v0=v0)
  File "/Users/pbinder/opt/anaconda3/envs/scRNA/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 532, in svds
    _, eigvec = eigsh(XH_X, k=k, tol=tol ** 2, maxiter=maxiter,
  File "/Users/pbinder/opt/anaconda3/envs/scRNA/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 1697, in eigsh
    params.iterate()
  File "/Users/pbinder/opt/anaconda3/envs/scRNA/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 573, in iterate
    raise ArpackError(self.info, infodict=self.iterate_infodict)
scipy.sparse.linalg._eigen.arpack.arpack.ArpackError: ARPACK error -9999: Could not build an Arnoldi factorization. IPARAM(5) returns the size of the current Arnoldi factorization. The user is advised to check that enough workspace and array storage has been allocated.

```

#### Versions:

> scvi-tools==0.20.3 python==3.9.16 scanpy==1.9.3 anndata==0.9.1 umap==0.5.3 numpy==1.23.5 scipy==1.10.1 pandas==1.5.3 scikit-learn==1.2.2 statsmodels==0.13.5 python-igraph==0.10.4 pynndescent==0.5.10

and macOS 13.2 (intel)

> 

Thanks
Patrick

**Comment by Zethson** [comment]
Since no one else reported this issue and a lot of people on Mac have run this tutorial, I'll close this for now. Maybe it has something to do with your specific machine and set up. If someone else encounters this, please let us know and I'll reopen this.
