### ISSUE TITLE
Error in importing scanpy when using scvi-tools

### ISSUE THREAD

**Issue by zacharyjxy2020** [scverse/scanpy#2542]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

I tried to import scanpy and got an error.

### Minimal code sample

```python
import scanpy as sc
```

### Error output

```pytb
Traceback (most recent call last):
  File "C:\Users\zacha\PycharmProjects\CellAssign\pipeline.py", line 2, in <module>
    import scanpy as sc
  File "C:\Users\zacha\.conda\envs\CellAssign\lib\site-packages\scanpy\__init__.py", line 6, in <module>
    from ._utils import check_versions
  File "C:\Users\zacha\.conda\envs\CellAssign\lib\site-packages\scanpy\_utils\__init__.py", line 21, in <module>
    from anndata import AnnData, __version__ as anndata_version
  File "C:\Users\zacha\.conda\envs\CellAssign\lib\site-packages\anndata\__init__.py", line 7, in <module>
    from ._core.anndata import AnnData
  File "C:\Users\zacha\.conda\envs\CellAssign\lib\site-packages\anndata\_core\anndata.py", line 17, in <module>
    import h5py
  File "C:\Users\zacha\.conda\envs\CellAssign\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "C:\Users\zacha\.conda\envs\CellAssign\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: The specified procedure could not be found.
```

### Versions

<details>

```

```

</details>

**Comment by Zethson** [comment]
You need to add more details

**Comment by Zethson** [comment]
Please reopen if the problem persists.
