### ISSUE TITLE
spaceranger2.0.1 outs/spatial/tissue_positions_list.csv change

### ISSUE THREAD

**Issue by hai178912522** [scverse/scanpy#2565]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

In scanpy version 1.9.3

### Minimal code sample

```python
adata = sc.read_visium(
  '/data_disk/ST01/User/zhanghh/project/analysis/GSM6252954/outs/',
  count_file='filtered_feature_bc_matrix.h5',
  source_image_path='/data_disk/ST01/User/zhanghh/project/GSE206391/GSM6252954_11-V19T12-012-V4.jpg',
)
```

### Error output

```pytb
/data_disk/ST01/Software/conda_env/zhhenv/lib/python3.9/site-packages/anndata/_core/anndata.py:1832: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhanghaihao/.local/lib/python3.9/site-packages/scanpy/readwrite.py", line 390, in read_visium
    raise OSError(f"Could not find '{f}'")
OSError: Could not find '/data_disk/ST01/User/zhanghh/project/analysis/GSM6252954/outs/spatial/tissue_positions_list.csv'
```

### Versions

<details>
<summary>Details</summary>

```
>>> import scanpy; scanpy.logging.print_versions()
-----
anndata     0.9.1
scanpy      1.9.3
-----
PIL                 9.4.0
beta_ufunc          NA
binom_ufunc         NA
cffi                1.15.1
colorama            0.4.6
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.2
dot_parser          NA
gmpy2               2.1.2
h5py                3.7.0
hypergeom_ufunc     NA
igraph              0.10.4
importlib_resources NA
invgauss_ufunc      NA
joblib              1.1.1
kiwisolver          1.4.4
leidenalg           0.9.1
llvmlite            0.40.0
matplotlib          3.7.1
mpl_toolkits        NA
mpmath              1.2.1
natsort             8.3.1
nbinom_ufunc        NA
ncf_ufunc           NA
nct_ufunc           NA
ncx2_ufunc          NA
numba               0.57.0
numpy               1.24.3
nvfuser             NA
opt_einsum          v3.3.0
packaging           23.0
pandas              2.0.1
pkg_resources       NA
pydot               1.4.2
pyparsing           3.0.9
pytz                2022.7
scipy               1.10.1
session_info        1.0.0
setuptools          66.0.0
six                 1.16.0
skewnorm_ufunc      NA
sklearn             1.2.2
sympy               1.11.1
texttable           1.6.7
threadpoolctl       2.2.0
torch               2.0.1
tqdm                4.65.0
typing_extensions   NA
yaml                6.0
zipp                NA
zoneinfo            NA
-----
Python 3.9.16 (main, Mar  8 2023, 14:00:05) [GCC 11.2.0]
Linux-5.15.0-71-generic-x86_64-with-glibc2.35
-----
Session information updated at 2023-07-20 15:11
```

</details>

**Comment by flying-sheep** [comment]
`tissue_positions_list.csv` is spaceranger 1.3, `tissue_positions.csv ` is spaceranger 2.0.

The code expects one of them:

https://github.com/scverse/scanpy/blob/05068c347ac176d664ada3b0d5979255d35ce686/scanpy/readwrite.py#L417-L421

Seems like you have none of them. We don’t support incomplete or otherwise nonstandard output directories.

If you think you have a normal output directory, please show us a directory listing and point us to the docs where the 10x people explain the changes.

**Comment by ktpolanski** [comment]
Can confirm that `tissue_positions.csv` is not properly detected in 1.9.3 installed off pip, but everything works fine in 1.10.0.dev87+gd08518f5 installed off GitHub.

**Comment by flying-sheep** [comment]
Seems like a release is in order. that code was merged in April
