### ISSUE TITLE
[scanpy_v1.9.6] pp.calculate_qc_metrics(anndata.h5ad) occured Data type conflic

### ISSUE THREAD

**Issue by OOAAHH** [scverse/scanpy#2758]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

While I am using `sc.pp.calculate_qc_metrics(ad, inplace=True)` to get QC metrics, its reported that a error occoured. 
Error message as below. 
﻿﻿
It might just be because there's something wrong with my data. Does anyone else have a similar situation?

### Minimal code sample

```python
import scanpy as sc
import numpy as np
import anndata

# ad = anndata.read_h5ad('mypath')

def scrublet_by_sample(ad, key='samplename'):
    """ do doublet prediction by batch/sample """
    """ ad = anndata object """
    """ key = sample or batch in ad.obs"""
    sc.pp.calculate_qc_metrics(ad, inplace=True)
    ads = []
    samplenames = ad.obs[key].unique()
    for i in samplenames:
        adx = ad[ad.obs[key].isin([i])].copy()
        print(i,adx.n_obs)
        sc.external.pp.scrublet(adx,n_prin_comps=min(30,adx.shape[0]-1))
        ads.append(adx)
    adata = ads[0].concatenate(tuple(ads[1:]), join='outer')
    return adata

if np.array_equal(arr, np.round(arr)):
    ad = scrublet_by_sample(ad, 'sample_ID')
    ad.write(qc_h5)
    qc_md5 = generate_file_md5(qc_h5)
    print("QC MD5 Hash:", qc_md5)
```

### Error output

```pytb
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 5, in scrublet_by_sample
  File "/home/sunhao/.conda/envs/h5ad/lib/python3.9/site-packages/scanpy/preprocessing/_qc.py", line 306, in calculate_qc_metrics
    obs_metrics = describe_obs(
  File "/home/sunhao/.conda/envs/h5ad/lib/python3.9/site-packages/scanpy/preprocessing/_qc.py", line 116, in describe_obs
    proportions = top_segment_proportions(X, percent_top)
  File "/home/sunhao/.conda/envs/h5ad/lib/python3.9/site-packages/scanpy/preprocessing/_qc.py", line 401, in top_segment_proportions
    return top_segment_proportions_sparse_csr(mtx.data, mtx.indptr, np.array(ns))
  File "/home/sunhao/.conda/envs/h5ad/lib/python3.9/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/sunhao/.conda/envs/h5ad/lib/python3.9/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function iadd>) found for signature:
 
 >>> iadd(array(bool, 1d, C), array(int64, 1d, C))
 
There are 18 candidate implementations:
   - Of which 14 did not match due to:
   Overload of function 'iadd': File: <numerous>: Line N/A.
     With argument(s): '(array(bool, 1d, C), array(int64, 1d, C))':
    No match.
   - Of which 2 did not match due to:
   Overload in function 'NumpyRulesInplaceArrayOperator.generic': File: numba/core/typing/npydecl.py: Line 243.
     With argument(s): '(array(bool, 1d, C), array(int64, 1d, C))':
    Rejected as the implementation raised a specific error:
      AttributeError: 'NoneType' object has no attribute 'args'
  raised from /home/sunhao/.conda/envs/h5ad/lib/python3.9/site-packages/numba/core/typing/npydecl.py:254
   - Of which 2 did not match due to:
   Operator Overload in function 'iadd': File: unknown: Line unknown.
     With argument(s): '(array(bool, 1d, C), array(int64, 1d, C))':
    No match for registered cases:
     * (int64, int64) -> int64
     * (int64, uint64) -> int64
     * (uint64, int64) -> int64
     * (uint64, uint64) -> uint64
     * (float32, float32) -> float32
     * (float64, float64) -> float64
     * (complex64, complex64) -> complex64
     * (complex128, complex128) -> complex128

During: typing of intrinsic-call at /home/sunhao/.conda/envs/h5ad/lib/python3.9/site-packages/scanpy/preprocessing/_qc.py (449)

File ".conda/envs/h5ad/lib/python3.9/site-packages/scanpy/preprocessing/_qc.py", line 449:
def top_segment_proportions_sparse_csr(data, indptr, ns):
    <source elided>
    for j in range(ns.size):
        acc += partitioned[:, prev : ns[j]].sum(axis=1)
```

### Versions

<details>

```
>>> import scanpy; scanpy.logging.print_versions()
-----
anndata     0.10.2
scanpy      1.9.6
-----
PIL                 10.0.1
beta_ufunc          NA
binom_ufunc         NA
cffi                1.15.1
cloudpickle         3.0.0
colorama            0.4.6
cycler              0.12.1
cython_runtime      NA
cytoolz             0.12.0
dask                2023.11.0
dateutil            2.8.2
exceptiongroup      1.1.3
fastcore            1.5.29
get_annotations     NA
h5py                3.7.0
hypergeom_ufunc     NA
importlib_resources NA
invgauss_ufunc      NA
joblib              1.3.2
kiwisolver          1.4.4
llvmlite            0.41.1
matplotlib          3.8.1
mkl                 2.4.0
mpl_toolkits        NA
natsort             8.4.0
nbinom_ufunc        NA
ncf_ufunc           NA
nct_ufunc           NA
ncx2_ufunc          NA
numba               0.58.1
numpy               1.23.5
packaging           23.2
pandas              1.2.4
psutil              5.9.0
pycparser           2.21
pyparsing           3.0.9
pytz                2023.3.post1
scDenorm            NA
scipy               1.10.1
session_info        1.0.0
setuptools          68.0.0
six                 1.16.0
skewnorm_ufunc      NA
sklearn             1.3.0
threadpoolctl       3.2.0
tlz                 0.12.0
toolz               0.12.0
tqdm                4.66.1
typing_extensions   NA
yaml                6.0
zipp                NA
-----
Python 3.9.13 (main, Oct 13 2022, 21:15:33) [GCC 11.2.0]
Linux-3.10.0-1160.102.1.el7.x86_64-x86_64-with-glibc2.17
-----
Session information updated at 2023-11-17 16:20
```

</details>

**Comment by flying-sheep** [comment]
Looks like your data is of boolean type. A `adata.X = adata.X.astype(np.int32)` could make that function work.

If that’s not it, we need to see your data or you giving us more detailed information about how it looks like!

If you need more help, please comment here and tell me so, then I’ll reopen this issue
