### ISSUE TITLE
missing scanpy components

### ISSUE THREAD

**Issue by zjgt** [scverse/scanpy#2949]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the main branch of scanpy.

### What happened?

I tried to do dpt trajectory analysis but constantly reminded of lacking this and that attributes. When I print out the components in the scanpy directory, it does seem to lack lots of components as shown below:

```
>>> print(dir(sc))
['AnnData', 'Neighbors', 'Verbosity', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_compat', '_metadata', '_settings', '_utils', 'concat', 'datasets', 'experimental', 'external', 'get', 'logging', 'metrics', 'neighbors', 'pl', 'plotting', 'pp', 'preprocessing', 'queries', 'read', 'read_10x_h5', 'read_10x_mtx', 'read_csv', 'read_excel', 'read_h5ad', 'read_hdf', 'read_loom', 'read_mtx', 'read_text', 'read_umi_tools', 'read_visium', 'readwrite', 'set_figure_params', 'settings', 'tl', 'tools', 'write']
```

I installed the latest version of scanpy 1.9.3 and python 3.9, my computer is MacBook Pro 2020.

### Minimal code sample

```python
>>> print(dir(sc))
['AnnData', 'Neighbors', 'Verbosity', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_compat', '_metadata', '_settings', '_utils', 'concat', 'datasets', 'experimental', 'external', 'get', 'logging', 'metrics', 'neighbors', 'pl', 'plotting', 'pp', 'preprocessing', 'queries', 'read', 'read_10x_h5', 'read_10x_mtx', 'read_csv', 'read_excel', 'read_h5ad', 'read_hdf', 'read_loom', 'read_mtx', 'read_text', 'read_umi_tools', 'read_visium', 'readwrite', 'set_figure_params', 'settings', 'tl', 'tools', 'write']
```

### Error output

```pytb
>>> print(dir(sc))
['AnnData', 'Neighbors', 'Verbosity', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_compat', '_metadata', '_settings', '_utils', 'concat', 'datasets', 'experimental', 'external', 'get', 'logging', 'metrics', 'neighbors', 'pl', 'plotting', 'pp', 'preprocessing', 'queries', 'read', 'read_10x_h5', 'read_10x_mtx', 'read_csv', 'read_excel', 'read_h5ad', 'read_hdf', 'read_loom', 'read_mtx', 'read_text', 'read_umi_tools', 'read_visium', 'readwrite', 'set_figure_params', 'settings', 'tl', 'tools', 'write']
```

### Versions

<details>

```

```

</details>
1.9.3

**Comment by flying-sheep** [comment]
I see `tl` in the list, so you type `sc.tl.dpt` as described in the documentation.

If you means something else, please tell us!

**Comment by zjgt** [comment]
sc.tl.dpt() itself is fine, but it seems to miss lots of components. Below are a couple of examples:
>>> root_mask = adata.obs['cell_type_tumor']=='Tumor cells LUAD NE'
>>> sc.tl.dpt(adata, xroot=root_mask)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: dpt() got an unexpected keyword argument 'xroot'
>>> sc.tl.root_cells(adata, root_mask)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scanpy.tools' has no attribute 'root_cells'
>>> root_vector = bdata[root_name, :].X.toarray().flatten()
>>> root_vector
array([0.37231696, 0.        , 0.        , ..., 0.37231696, 0.        ,
       0.        ], dtype=float32)
>>> adata.var['xroot']= root_vector
>>> sc.tl.dpt(adata)
WARNING: Trying to run `tl.dpt` without prior call of `tl.diffmap`. Falling back to `tl.diffmap` with default parameters.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/scanpy/tools/_dpt.py", line 136, in dpt
    _diffmap(adata, neighbors_key=neighbors_key)
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/scanpy/tools/_dpt.py", line 15, in _diffmap
    dpt = DPT(adata, neighbors_key=neighbors_key)
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/scanpy/tools/_dpt.py", line 207, in __init__
    super().__init__(adata, n_dcs=n_dcs, neighbors_key=neighbors_key)
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/scanpy/neighbors/__init__.py", line 584, in __init__
    self._init_iroot()
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/scanpy/neighbors/__init__.py", line 1027, in _init_iroot
    self._set_iroot_via_xroot(xroot)
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/scanpy/neighbors/__init__.py", line 1084, in _set_iroot_via_xroot
    diff = self._adata.X[i, :] - xroot
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/pandas/core/arraylike.py", line 104, in __rsub__
    return self._arith_method(other, roperator.rsub)
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/pandas/core/series.py", line 5528, in _arith_method
    return self._construct_result(result, name=res_name)
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/pandas/core/series.py", line 2945, in _construct_result
    out = self._constructor(result, index=self.index)
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/pandas/core/series.py", line 430, in __init__
    com.require_length_match(data, index)
  File "/usr/local/Caskroom/miniconda/base/envs/pscanpy/lib/python3.7/site-packages/pandas/core/common.py", line 532, in require_length_match
    "Length of values "
ValueError: Length of values (1) does not match length of index (5985)
