### ISSUE TITLE
module 'scanpy.api.tools' has no attribute 'diffrank'

### ISSUE THREAD

**Issue by zacharylau10** [scverse/scanpy#30]
hi, 
I installed the scanpy-master , but when I type `scanpy --help` in bash the error occurred. I noticed that diffrank was replaced by rank_genes_groups, but I don't know how to fix it. 
```
Traceback (most recent call last):
  File "/public/bioapps/ana/anaconda3/envs/python35/bin/scanpy", line 11, in <module>
    load_entry_point('scanpy==0+unknown', 'console_scripts', 'scanpy')()
  File "/public/bioapps/ana/anaconda3/envs/python35/lib/python3.5/site-packages/scanpy-0+unknown-py3.5-linux-x86_64.egg/scanpy/__main__.py", line 278, in main
    init_main_parser().print_help()
  File "/public/bioapps/ana/anaconda3/envs/python35/lib/python3.5/site-packages/scanpy-0+unknown-py3.5-linux-x86_64.egg/scanpy/__main__.py", line 117, in init_main_parser
    descr = 78*'-' + '\n' + getattr(tools, key).__doc__
AttributeError: module 'scanpy.api.tools' has no attribute 'diffrank'

```

**Comment by falexwolf** [comment]
Hi!
Sorry for that, the command-line interface got a bit behind. I fixed everything, simply pull again.
Cheers,
  Alex

**Comment by zacharylau10** [comment]
Thanks for that! @falexwolf
