### ISSUE TITLE
sc.pl.stacked_violin: issue using imported adata

### ISSUE THREAD

**Issue by bebatut** [scverse/scanpy#318]
Hi,

I am testing `sc.pl.stacked_violin` and I had an issue with running it on an AnnData variable that is imported from a `h5ad` file. I explain.

If I run:

```
>>> import scanpy.api as sc
>>> adata = sc.datasets.krumsiek11()
>>> sc.pl.stacked_violin(adata, adata.var_names, 'cell_type', use_raw=False, color='blue', show=False)
```

No problem, but if I run:

```
>>> import scanpy.api as sc
>>> adata = sc.datasets.krumsiek11()
>>> adata.write('anndata.h5ad')
>>> adata = sc.read_h5ad('anndata.h5ad')
>>> sc.pl.stacked_violin(adata, adata.var_names, 'cell_type', use_raw=False, color='blue', show=False)
```

then I got the error:

```
Traceback (most recent call last):
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/scanpy/lib/python3.6/site-packages/scanpy/plotting/anndata.py", line 896, in stacked_violin
    orient='vertical', scale=scale, ax=ax, **kwds)
  File "/miniconda3/envs/scanpy/lib/python3.6/site-packages/seaborn/categorical.py", line 2387, in violinplot
    color, palette, saturation)
  File "/miniconda3/envs/scanpy/lib/python3.6/site-packages/seaborn/categorical.py", line 562, in __init__
    self.establish_variables(x, y, hue, data, orient, order, hue_order)
  File "/miniconda3/envs/scanpy/lib/python3.6/site-packages/seaborn/categorical.py", line 155, in establish_variables
    raise ValueError(err)
ValueError: Could not interpret input 'variable'
```

I tested it with versions 1.3.1 and 1.3.2, installed with bioconda.

Any idea?

Bérénice

**Comment by fidelram** [comment]
Very strange. `variable` is some assigned name after an internal `pandas.melt`. 

First, I would not recommend to plot all  `adata.var_names` unless they are fewer (<30). But that seems not to be the problem.

To discard a problem with seaborn violin plot, can you try `sc.pl.matrixplot` instead?

Also, do you get the same output in both cases after

```
adata.obs.head()
```

**Comment by bebatut** [comment]
Not exactly the same head:

```
>>> adata = sc.datasets.krumsiek11()
>>> adata.obs.head()
    cell_type
0  progenitor
1  progenitor
2  progenitor
3  progenitor
4  progenitor
>>> adata.write('anndata.h5ad')
>>> adata = sc.read_h5ad('anndata.h5ad')
>>> adata.obs.head()
        cell_type
index
0      progenitor
1      progenitor
2      progenitor
3      progenitor
4      progenitor
```

**Comment by fidelram** [comment]
Can you try:
```
sc.pl.stacked_violin(adata, adata.var_names[:10], groupby='cell_type',
use_raw=False, color='blue', show=False)
```
The second parameter for stakec_violin is a list of genes, but it should be
on a range that is amenable for plotting meaning <30 genes. In your example
you provide most likely thousands. I don't know if the error is related to
this but we can narrow down the problem.

Maybe the examples here can help you:
https://gist.github.com/fidelram/2289b7a8d6da055fb058ac9a79ed485c

**Comment by fidelram** [comment]
I can reproduce the problem. I will take a look

**Comment by bebatut** [comment]
Thanks a lot
