### ISSUE TITLE
dimension flattening error when slicing

### ISSUE THREAD

**Issue by bkmartinjr** [scverse/scanpy#332]
Slicing causes inconsistent state when either n_obs or n_vars == 1, resulting in a slice that can no longer be sliced again on the other axis, due to shape inconsistencies between the AnnData and X object.

anndata 0.6.11, scanpy 1.3.2, WSL/Ubuntu

Test case:
```
import scanpy.api as sc
data = sc.read('example-dataset/data.h5ad')
>>> data.shape, data.X.shape, data._X.shape
((2638, 1838), (2638, 1838), (2638, 1838))
>>> slice = data[0, :]
>>> slice.shape, slice.X.shape, slice._X.shape
((1, 1838), (1838,), (1, 1838))
>>> slice[:, 0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 1303, in __getitem__
    return self._getitem_view(index)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 1307, in _getitem_view
    return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 669, in __init__
    self._init_as_view(X, oidx, vidx)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 726, in _init_as_view
    self._init_X_as_view()
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 741, in _init_X_as_view
    X = self._adata_ref.X[self._oidx, self._vidx]
IndexError: too many indices for array
>>> slice[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 1303, in __getitem__
    return self._getitem_view(index)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 1307, in _getitem_view
    return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 669, in __init__
    self._init_as_view(X, oidx, vidx)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 726, in _init_as_view
    self._init_X_as_view()
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 741, in _init_X_as_view
    X = self._adata_ref.X[self._oidx, self._vidx]
IndexError: too many indices for array
```

Should base.py, line 741 be a reference to _X rather than X?

**Comment by bkmartinjr** [comment]
Addendum: different errors are generated depending on which axis is first sliced.   The data set I'm loading is a dense matrix.

```
>>> data.X.dtype
dtype('<f4')
>>> data[:,0][0,:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 1303, in __getitem__
    return self._getitem_view(index)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 1307, in _getitem_view
    return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 669, in __init__
    self._init_as_view(X, oidx, vidx)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 694, in _init_as_view
    uns_new = deepcopy(self._adata_ref._uns)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 307, in _reconstruct
    y[key] = value
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 444, in __setitem__
    _init_actual_AnnData(adata_view)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 367, in _init_actual_AnnData
    adata_view._init_as_actual(adata_view.copy())
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 880, in _init_as_actual
    self._check_dimensions()
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 1879, in _check_dimensions
    .format(self._n_obs, self._obs.shape[0]))
ValueError: Observations annot. `obs` must have number of rows of `X` (1), but has 2638 rows.
>>> data[0,:][:,0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 1303, in __getitem__
    return self._getitem_view(index)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 1307, in _getitem_view
    return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 669, in __init__
    self._init_as_view(X, oidx, vidx)
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 726, in _init_as_view
    self._init_X_as_view()
  File "/cellxgene/venv/lib/python3.6/site-packages/anndata/base.py", line 741, in _init_X_as_view
    X = self._adata_ref.X[self._oidx, self._vidx]
IndexError: too many indices for array
```

**Comment by bkmartinjr** [comment]
More comprehensive test, similar to the current AnnData slicing tests (no use of external data).  Each try/except block will (currently) fail on its last assertion.

```
import sys, traceback
import numpy as np
import scanpy.api as sc

adata = sc.AnnData(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

# integer indexing
print("\n>>> integer indexing, obs first")
try:
    assert adata[0:2, :][:, 0:2].X.tolist() == [[1,2], [4,5]]
    assert adata[0, 0].X.tolist() == 1
    assert adata[0:1, 0:1].X.tolist() == 1
    assert adata[0, :][:, 0].X.tolist() == 1

except Exception as e:
    traceback.print_exc(file=sys.stdout)

print("\n>>> integer indexing, vars first")
try:
    assert adata[:, 0:2][0:2, :].X.tolist() == [[1,2], [4,5]]
    assert adata[0, 0].X.tolist() == 1
    assert adata[0:1, 0:1].X.tolist() == 1
    assert adata[:, 0][0, :].X.tolist() == 1

except Exception as e:
    traceback.print_exc(file=sys.stdout)

# boolean indexing
print("\n>>> boolean indexing, obs first")
try:
    obs_selector = np.zeros(len(adata.obs), dtype=bool)
    vars_selector = np.zeros(len(adata.var), dtype=bool)

    obs_selector[:] = [True, True, False]
    vars_selector[:] = [True, True, False]
    assert adata[obs_selector, :][:, vars_selector].X.tolist() == [[1,2], [4,5]]

    obs_selector[:] = [True, False, False]
    vars_selector[:] = [True, False, False]
    assert adata[obs_selector, :][:, vars_selector].X.tolist() == 1

except Exception as e:
    traceback.print_exc(file=sys.stdout)

print("\n>>> boolean indexing, vars first")
try:
    obs_selector = np.zeros(len(adata.obs), dtype=bool)
    vars_selector = np.zeros(len(adata.var), dtype=bool)

    obs_selector[:] = [True, True, False]
    vars_selector[:] = [True, True, False]
    assert adata[:, vars_selector][obs_selector, :].X.tolist() == [[1,2], [4,5]]

    obs_selector[:] = [True, False, False]
    vars_selector[:] = [True, False, False]
    assert adata[:, vars_selector][obs_selector, :].X.tolist() == 1

except Exception as e:
    traceback.print_exc(file=sys.stdout)
```

**Comment by falexwolf** [comment]
Fixed via https://github.com/theislab/anndata/commit/a8dfef5aaa7b852b2b9eaeba0ed83f0b3d282d2a.
