### ISSUE TITLE
`pip3 install scanpy` -> 'TypeError: Can't convert 'list' object to str implicitly'

### ISSUE THREAD

**Issue by setgree** [scverse/scanpy#355]
This is in an Ubuntu 16..04 Docker container:
```
docker run --rm -it ubuntu:16.04
```
Then I ran:
```
apt-get update && apt-get install -y \
  python3-pip \
  python3-setuptools
  python3-wheel

pip3 install scanpy
```

I get the following output (after all of the dependencies are downloaded):

```
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'scanpy.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'scanpy.egg-info/SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-33o4crd7/scanpy/setup.py", line 51, in <module>
      'Topic :: Scientific/Engineering :: Visualization',
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-33o4crd7/scanpy/versioneer.py", line 1559, in run
      _build_py.run(self)
    File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 52, in run
      self.build_package_data()
    File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 107, in build_package_data
      for package, src_dir, build_dir, filenames in self.data_files:
    File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 65, in __getattr__
      self.data_files = self._get_data_files()
    File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 79, in _get_data_files
      return list(map(self._get_pkg_data_files, self.packages or ()))
    File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 91, in _get_pkg_data_files
      for file in self.find_data_files(package, src_dir)
    File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 98, in find_data_files
      + self.package_data.get(package, []))
  TypeError: Can't convert 'list' object to str implicitly
  
  ----------------------------------------
  Failed building wheel for scanpy
  Running setup.py clean for scanpy
  Running setup.py bdist_wheel for anndata ... done
  Stored in directory: /root/.cache/pip/wheels/f1/f0/02/ea67db3107825884bae91e3806e425718f10062c631e2b1367
  Running setup.py bdist_wheel for networkx ... done
  Stored in directory: /root/.cache/pip/wheels/68/f8/29/b53346a112a07d30a5a84d53f19aeadaa1a474897c0423af91
Successfully built anndata networkx
Failed to build scanpy
Installing collected packages: six, python-dateutil, pytz, numpy, pandas, scipy, h5py, natsort, anndata, pyparsing, cycler, kiwisolver, matplotlib, seaborn, numexpr, tables, scikit-learn, patsy, statsmodels, decorator, networkx, joblib, llvmlite, numba, scanpy
  Running setup.py install for scanpy ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-33o4crd7/scanpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-65l8zi0l-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/scanpy
    copying scanpy/settings.py -> build/lib/scanpy
    copying scanpy/readwrite.py -> build/lib/scanpy
    copying scanpy/_version.py -> build/lib/scanpy
    copying scanpy/__init__.py -> build/lib/scanpy
    copying scanpy/utils.py -> build/lib/scanpy
    copying scanpy/logging.py -> build/lib/scanpy
    copying scanpy/exporting.py -> build/lib/scanpy
    creating build/lib/scanpy/preprocessing
    copying scanpy/preprocessing/recipes.py -> build/lib/scanpy/preprocessing
    copying scanpy/preprocessing/highly_variable_genes.py -> build/lib/scanpy/preprocessing
    copying scanpy/preprocessing/__init__.py -> build/lib/scanpy/preprocessing
    copying scanpy/preprocessing/magic.py -> build/lib/scanpy/preprocessing
    copying scanpy/preprocessing/dca.py -> build/lib/scanpy/preprocessing
    copying scanpy/preprocessing/mnn_correct.py -> build/lib/scanpy/preprocessing
    copying scanpy/preprocessing/qc.py -> build/lib/scanpy/preprocessing
    copying scanpy/preprocessing/simple.py -> build/lib/scanpy/preprocessing
    creating build/lib/scanpy/datasets
    copying scanpy/datasets/__init__.py -> build/lib/scanpy/datasets
    copying scanpy/datasets/api_without_datasets.py -> build/lib/scanpy/datasets
    creating build/lib/scanpy/queries
    copying scanpy/queries/__init__.py -> build/lib/scanpy/queries
    creating build/lib/scanpy/api
    copying scanpy/api/__init__.py -> build/lib/scanpy/api
    copying scanpy/api/datasets.py -> build/lib/scanpy/api
    copying scanpy/api/export_to.py -> build/lib/scanpy/api
    copying scanpy/api/tl.py -> build/lib/scanpy/api
    copying scanpy/api/pl.py -> build/lib/scanpy/api
    copying scanpy/api/queries.py -> build/lib/scanpy/api
    copying scanpy/api/logging.py -> build/lib/scanpy/api
    copying scanpy/api/pp.py -> build/lib/scanpy/api
    creating build/lib/scanpy/tools
    copying scanpy/tools/dpt.py -> build/lib/scanpy/tools
    copying scanpy/tools/phate.py -> build/lib/scanpy/tools
    copying scanpy/tools/diffmap.py -> build/lib/scanpy/tools
    copying scanpy/tools/score_genes.py -> build/lib/scanpy/tools
    copying scanpy/tools/_utils.py -> build/lib/scanpy/tools
    copying scanpy/tools/__init__.py -> build/lib/scanpy/tools
    copying scanpy/tools/umap.py -> build/lib/scanpy/tools
    copying scanpy/tools/rank_genes_groups.py -> build/lib/scanpy/tools
    copying scanpy/tools/pca.py -> build/lib/scanpy/tools
    copying scanpy/tools/paga.py -> build/lib/scanpy/tools
    copying scanpy/tools/pypairs.py -> build/lib/scanpy/tools
    copying scanpy/tools/tsne.py -> build/lib/scanpy/tools
    copying scanpy/tools/louvain.py -> build/lib/scanpy/tools
    copying scanpy/tools/_tsne_fix.py -> build/lib/scanpy/tools
    copying scanpy/tools/draw_graph.py -> build/lib/scanpy/tools
    copying scanpy/tools/sim.py -> build/lib/scanpy/tools
    copying scanpy/tools/rna_velocity.py -> build/lib/scanpy/tools
    copying scanpy/tools/top_genes.py -> build/lib/scanpy/tools
    creating build/lib/scanpy/rtools
    copying scanpy/rtools/__init__.py -> build/lib/scanpy/rtools
    copying scanpy/rtools/mnn_correct.py -> build/lib/scanpy/rtools
    creating build/lib/scanpy/sim_models
    copying scanpy/sim_models/__init__.py -> build/lib/scanpy/sim_models
    creating build/lib/scanpy/plotting
    copying scanpy/plotting/docs.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/__init__.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/rcmod.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/palettes.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/top_genes_visual.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/utils.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/preprocessing.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/qc.py -> build/lib/scanpy/plotting
    copying scanpy/plotting/anndata.py -> build/lib/scanpy/plotting
    creating build/lib/scanpy/neighbors
    copying scanpy/neighbors/__init__.py -> build/lib/scanpy/neighbors
    creating build/lib/scanpy/preprocessing/_deprecated
    copying scanpy/preprocessing/_deprecated/highly_variable_genes.py -> build/lib/scanpy/preprocessing/_deprecated
    copying scanpy/preprocessing/_deprecated/__init__.py -> build/lib/scanpy/preprocessing/_deprecated
    creating build/lib/scanpy/plotting/tools
    copying scanpy/plotting/tools/scatterplots.py -> build/lib/scanpy/plotting/tools
    copying scanpy/plotting/tools/__init__.py -> build/lib/scanpy/plotting/tools
    copying scanpy/plotting/tools/paga.py -> build/lib/scanpy/plotting/tools
    creating build/lib/scanpy/neighbors/umap
    copying scanpy/neighbors/umap/distances.py -> build/lib/scanpy/neighbors/umap
    copying scanpy/neighbors/umap/__init__.py -> build/lib/scanpy/neighbors/umap
    copying scanpy/neighbors/umap/umap_.py -> build/lib/scanpy/neighbors/umap
    copying scanpy/neighbors/umap/sparse.py -> build/lib/scanpy/neighbors/umap
    copying scanpy/neighbors/umap/utils.py -> build/lib/scanpy/neighbors/umap
    running egg_info
    writing dependency_links to scanpy.egg-info/dependency_links.txt
    writing scanpy.egg-info/PKG-INFO
    writing top-level names to scanpy.egg-info/top_level.txt
    writing requirements to scanpy.egg-info/requires.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'scanpy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'scanpy.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-33o4crd7/scanpy/setup.py", line 51, in <module>
        'Topic :: Scientific/Engineering :: Visualization',
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-33o4crd7/scanpy/versioneer.py", line 1559, in run
        _build_py.run(self)
      File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 52, in run
        self.build_package_data()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 107, in build_package_data
        for package, src_dir, build_dir, filenames in self.data_files:
      File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 65, in __getattr__
        self.data_files = self._get_data_files()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 79, in _get_data_files
        return list(map(self._get_pkg_data_files, self.packages or ()))
      File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 91, in _get_pkg_data_files
        for file in self.find_data_files(package, src_dir)
      File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 98, in find_data_files
        + self.package_data.get(package, []))
    TypeError: Can't convert 'list' object to str implicitly
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-33o4crd7/scanpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-65l8zi0l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-33o4crd7/scanpy/
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Same error message after upgrading pip.

Thank you!

**Comment by setgree** [comment]
Update: the issue is that `apt-get install -y python3-pip` installs Python version 3.5.2. You would need to upgrade to version 3.6, as the readme suggests.
