### ISSUE TITLE
Github install error

### ISSUE THREAD

**Issue by veghp** [scverse/scanpy#482]
Tried to install via  `$ pip3 install -e .`  but returned this error:
```
Obtaining file://path/to/scanpy_1.4/scanpy
    Complete output from command python setup.py egg_info:
    /path/to/miniconda3/envs/bio/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
      from ._conv import register_converters as _register_converters
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "path/to/scanpy/setup.py", line 11, in <module>
        from scanpy import __author__, __email__
      File "path/to/scanpy/scanpy/__init__.py", line 26, in <module>
        check_versions()
      File "path/to/scanpy/scanpy/utils.py", line 38, in check_versions
        .format(__version__, anndata.__version__))
    NameError: name '__version__' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in path/to/scanpy/
```
The variable `__version__` in line 38 in utils.py is not defined.

**Comment by veghp** [comment]
In any case, running:  `$ pip install anndata -U --no-deps`  solves the problem, as then the problematic part of utils.py is not run.

**Comment by flying-sheep** [comment]
Thank you!
