### ISSUE TITLE
PAGA plotting error

### ISSUE THREAD

**Issue by veghp** [scverse/scanpy#487]
Running `sc.pl.paga(adata)` in v1.4 returns an error:
```
Traceback (most recent call last):

  File "<ipython-input-412-3baa85828ec9>", line 1, in <module>
    sc.pl.paga(adata)

  File "/path/to/scanpy/scanpy/plotting/_tools/paga.py", line 445, in paga
    adjacency_solid, layout=layout, random_state=random_state, init_pos=init_pos, layout_kwds=layout_kwds, adj_tree=adj_tree, root=root)

UnboundLocalError: local variable 'adj_tree' referenced before assignment
```

There is a conditional before the referenced line, which assigns value to `adj_tree`, and indeed, running these works fine:
```
sc.pl.paga(adata, layout='rt')
sc.pl.paga(adata, layout='rt_circular')
sc.pl.paga(adata, layout='eq_tree')
```

**Comment by veghp** [comment]
Solved here: https://github.com/theislab/scanpy/issues/483
