### ISSUE TITLE
Scanpy does not work with with few permissions

### ISSUE THREAD

**Issue by ChristianSauer** [scverse/scanpy#50]
I'm running scanpy in a docker container with few privileges, e.g. the guest user.
Unfortunately, scanpy tries to create a folder in the local working directory:

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/scanpy/__init__.py", line 14, in <module>
    from . import settings
  File "/usr/local/lib/python3.6/site-packages/scanpy/settings.py", line 13, in <module>
    os.makedirs('.scanpy/')
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '.scanpy/'
```

Could you use a tempdir alternativley?

**Comment by flying-sheep** [comment]
i think the reason we do this is for project-specific caching, not temporary files.

using the dedicated cache dir is of course preferable to using the working dir, since the OS knows about them (and can clean them once prompted or necessary), and preferable to a tempdir, as they survive restarts.

we should use <code>cache_dir = Path([appdirs](https://pypi.python.org/pypi/appdirs/1.4.3).user_cache_dir('scanpy', 'F. Alex Wolf'))</code>

**Comment by falexwolf** [comment]
The reason for this directory is just project-specific configuration.

Here, https://github.com/theislab/scanpy/commit/7a57fd4cf140dc4b2ffca7ef0651a355c74f0122, I removed the creation of this directory.

Nonetheless, it's true that Scanpy, when you tell it to cache a file, it wants to create a directory (by default './write/') for it. Tell me if this is a problem for you.

**Comment by flying-sheep** [comment]
ah, yes, i confused `.scanpy` and `.write`.

i think caching in a real cache directory instead of `./.write` would be better in any case.

**Comment by falexwolf** [comment]
It's `'./write/'`, so it's not a hidden directory - i guess it wouldn't be a good idea to save large files in a hidden fashion; whereas the config was hidden in `'.scanpy/'` - but the latter is not really needed anymore and I could simply remove it.

**Comment by ChristianSauer** [comment]
I think write is ok, since there is an option to move /write/ around.
As a suggestion:
Per default try to write into /write/ - if this does not work for any reason, grab a tempdirectory (tempfile module in python) and use that. Print a warning for the user. Then I would always work.

Edit: A temp directory taken from tempfile would have the added bonus that the system could clean it up. But for some usecases (LARGE files...) it would be great to control the folder location as is

**Comment by flying-sheep** [comment]
i dimly remember that another project decided against that. it’s confusing if suddenly the directory becomes writable and then scanpy creates a second one.

i’d say:

```py
class Writedir:
    def __enter__(self):
        return Path(sett.writedir)
    def __exit__(self, exc_type, exc_val, exc_tb):
        if issubclass(exc_type, PermissionError):
            errno, reason = exc_val.args
            exc_val.args = (errno, f'{reason}. Try to set sc.sett.writedir to e.g.: {cache_dir}')
writedir_context = Writedir()
del Writedir
```

and now each time we use it, we do:

```py
with writedir_context as writedir:
    (writedir / 'blah').open('w')

**Comment by ChristianSauer** [comment]
I like the idea.
You could probably avoid the context manager but it's ok I think.-

**Comment by flying-sheep** [comment]
how would you avoid the context manager?

it’s either that or wrapping try/catch around every single use of the `writedir`.

**Comment by falexwolf** [comment]
OK, will talk to Philipp about this in Person... This only concerns speeding up the reading of slow (e.g., text-based) data file formats.

This might also be relevant for this discussion: foreseeing the use of partially loaded data into memory, files for backing AnnData remain something the user has to actively interact with. With the creation of an AnnData object, she/he would then have the option to create a corresponding "backing-file", which is internally used by AnnData to load needed parts into memory and leave parts that are not needed on the disk. At any time when there is no active write or read to the file, the file stores the current state of AnnData.

I felt that both cache files and "backing files" should happen in a project-specific './write' directory - that is, at a location where an inexperienced user directly "sees" what happens and how this affects disk space. One could think about renaming the "data" subdirectory to something like "data_cache" or so to make evident that this only stores cache files, which can simply be deleted, and everything else stores "AnnData backing files" = "result files" or exported files...

But I agree true cache files might be better placed in a tmp directory. As said, will discuss this.

**Comment by flying-sheep** [comment]
sure, we’ll talk in 10 days or so, after my holidays 😄

except if you want to earlier, then we can skype or so.

> One could think about renaming the "data" subdirectory to something like "data_cache" or so to make evident that this only stores cache files, which can simply be deleted, and everything else stores "AnnData backing files" = "result files" or exported files...

definitely

> But I agree true cache files might be better placed in a tmp directory

no, as i said: cache directory, not temp directory. both have (overridable) standard locations on all OSs. e.g. on linux:

- `$TMPDIR` or `/tmp/`: temporary means that the files are only to be read during the same function/script execution, and deleted after. temp files forgotten by the application that created them are deleted after `$TMPTIME` and on reboot. (on linux now usually because `/tmp/` is a ramdisk and RAM contents don’t survive a reboot)

    ```py
    # python gives you a context manager that deletes the file after its block
    with tempfile.TemporaryFile() as fp:
        use(fp)
    # fp and the file are gone now
    ```

- `$XDG_CACHE_HOME` or `~/.cache/`: cache files are permanent until the user or OS cleans up or the application decides it no longer needs them (i think e.g. browsers clear out the parts of their cache periodically).

since scanpy has a notion of a project directory, putting the cache there is OK as well. the advantage is visibility, but that only works if the user knows what the directory/ies are for. using `cache` in the name of the cache directory would certainly help to signify that the stuff can be safely deleted.
