### ISSUE TITLE
AnnData.write() requires path specification

### ISSUE THREAD

**Issue by jorvis** [scverse/scanpy#66]
I have a short script which reads a tab file and writes h5 using scanpy.  I've found that unless I provide a full path to the write() function or at least a relative one via "./foo.h5" it fails.  Simplified version:

```py
adata = sc.read(args.input_file, ext='txt', first_column_names=True).transpose()
adata.write('./test.h5')   # this works
adata.write('test2.h5')   # this fails
```

Here's the stack:

```pytb
WARNING: This might be very slow. Consider passing `cache=True`, which enables much faster reading from a cache file.
Traceback (most recent call last):
  File "./convert_gear_group_single_cell_to_hdf5.py", line 47, in <module>
    main()
  File "./convert_gear_group_single_cell_to_hdf5.py", line 43, in main
    adata.write('test2.h5')
  File "/usr/local/lib/python3.5/dist-packages/anndata/base.py", line 1471, in write
    compression=compression, compression_opts=compression_opts)
  File "/usr/local/lib/python3.5/dist-packages/anndata/base.py", line 1513, in _write_h5ad
    os.makedirs(os.path.dirname(filename))
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
_____________________________

```

**Comment by falexwolf** [comment]
Should be solved since anndata 0.5.8.
