### ISSUE TITLE
sc.pp.highly_variable_genes: overflow encountered

### ISSUE THREAD

**Issue by sjfleming** [scverse/scanpy#763]
Env:
* Ubuntu 16.04
* python 3.7
* pandas 0.25.0
* scanpy 1.4.4.post1

I have an AnnData object called `adata`.  The maximum value in the count matrix `adata.X` is 3701.

When I do
`sc.pp.highly_variable_genes(adata)`

I get the following error
```
/home/sfleming/anaconda3/envs/scvi/lib/python3.7/site-packages/scipy/sparse/data.py:132: RuntimeWarning: overflow encountered in expm1
  result = op(self._deduped_data())
/home/sfleming/anaconda3/envs/scvi/lib/python3.7/site-packages/scipy/sparse/data.py:132: RuntimeWarning: invalid value encountered in expm1
  result = op(self._deduped_data())
/home/sfleming/anaconda3/envs/scvi/lib/python3.7/site-packages/scanpy/preprocessing/_utils.py:18: RuntimeWarning: overflow encountered in square
  var = (mean_sq - mean**2) * (X.shape[0]/(X.shape[0]-1))
/home/sfleming/anaconda3/envs/scvi/lib/python3.7/site-packages/scanpy/preprocessing/_utils.py:18: RuntimeWarning: invalid value encountered in subtract
  var = (mean_sq - mean**2) * (X.shape[0]/(X.shape[0]-1))
/home/sfleming/anaconda3/envs/scvi/lib/python3.7/site-packages/scanpy/preprocessing/_highly_variable_genes.py:86: RuntimeWarning: overflow encountered in log1p
  mean = np.log1p(mean)
/home/sfleming/anaconda3/envs/scvi/lib/python3.7/site-packages/scanpy/preprocessing/_highly_variable_genes.py:86: RuntimeWarning: invalid value encountered in log1p
  mean = np.log1p(mean)
Traceback (most recent call last):
  File "../../scvi/scvi_adata.py", line 75, in <module>
    sc.pp.highly_variable_genes(adata)
  File "/home/sfleming/anaconda3/envs/scvi/lib/python3.7/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 257, in highly_variable_genes
    flavor=flavor)
  File "/home/sfleming/anaconda3/envs/scvi/lib/python3.7/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 92, in _highly_variable_genes_single_batch
    df['mean_bin'] = pd.cut(df['means'], bins=n_bins)
  File "/home/sfleming/anaconda3/envs/scvi/lib/python3.7/site-packages/pandas/core/reshape/tile.py", line 233, in cut
    "cannot specify integer `bins` when input data " "contains infinity"
ValueError: cannot specify integer `bins` when input data contains infinity
```

Indeed, if I do `np.expm1(3701)` I get an overflow.

I think it will be necessary to come up with a way to calculate highly variable genes without doing `expm1` on the raw counts, due to this overflow issue.

**Comment by sjfleming** [comment]
Either that, or allow the downstream code to gracefully handle `inf` values.
It is the binning procedure for both 'seurat' and 'cell_ranger' that seem to be a problem.

**Comment by sjfleming** [comment]
Sorry, just realizing that this function expects logarithmized data.  My fault.

**Comment by maximilianh** [comment]
Still the error message could be a lot better. I’ve made the same mistake,
it’s easy to forget to log the data.

**Comment by emdann** [comment]
The same error in `sc.pp.highly_variable_genes` can pop up also if you forget to `sc.pp.filter_genes(adata, min_cells=0)` before running normalization and logging. Some informative error messages could for sure save some time here.

**Comment by seqyuan** [comment]
do not `sc.pp.scale(adata)` before use `sc.pp.highly_variable_genes` will not show the error

**Comment by ramadatta** [comment]
Thanks, all I had to do was:

```
# Log-transform the data
sc.pp.log1p(adata)
```
