### ISSUE TITLE
sc.tl.rank_genes_groups() for same cluster but different batch

### ISSUE THREAD

**Issue by grimwoo** [scverse/scanpy#838]
Hi, if I had 3 batch (sample01, sample02, and sample03) and 18 clusters (louvain), how could I find the differentially expressed gene between [A] and [B].
[A] refers to [cluster 1, 2, 3 in **sample01** and **sample02**] 
[B] refers to [cluster 2 and 3 in  **sample03**]

**Comment by ivirshup** [comment]
Would something like this work?

```python
adata.obs["comparison"] = np.nan
adata.obs.loc[
    adata.obs["batch"].isin(["sample01", "sample02"]) & adata.obs["leiden"].isin(["1", "2", "3"]),
    "comparison"
] = "A"
adata.obs.loc[
    (adata.obs["batch"] == "sample03") & adata.obs["leiden"].isin(["2", "3"]),
    "comparison"
] = "B"

sc.tl.rank_genes_groups(adata, "comparison", reference="B", n_genes=adata.shape[1])
sc.get.rank_genes_groups_df(adata, "A")
```

**Comment by grimwoo** [comment]
@ivirshup 
Hi, thank for your help.
When I ran this code (sc.tl.rank_genes_groups(adata, "comparison", reference="B", n_genes=adata.shape[1]); the previous three code worked perfectly), I got some error. I don't know whether they came from the scanpy module or something else.

```python
>>> import scanpy as sc
>>> sc.tl.rank_genes_groups(adata, "comparison", reference="B", n_genes=adata.shape[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/scanpy/tools/_rank_genes_groups.py", line 120, in rank_genes_groups
    groups_order += [reference]
TypeError: must be str, not list


>>> import scanpy.api as sc
>>> sc.tl.rank_genes_groups(adata, "comparison", reference="B", n_genes=adata.shape[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/scanpy/tools/_rank_genes_groups.py", line 120, in rank_genes_groups
    groups_order += [reference]
TypeError: must be str, not list


>>> import scanpy.external as sc
>>> sc.tl.rank_genes_groups(adata, "comparison", reference="B", n_genes=adata.shape[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scanpy.external.tl' has no attribute 'rank_genes_groups'
```

**Comment by flying-sheep** [comment]
Hi! You shouldn’t need to try here: Read the documentation at https://scanpy.rtfd.io to figure out if what you want is in `scanpy` or `scanpy.external`. `scanpy.api` is deprecated, you should never use it.

The code @ivirshup gave you will work in the next scanpy release, as scanpy 1.4.4 still has the bug  #346. Please upgrade to scanpy from git master and try again. You can do that via:

```bash
pip install git+https://github.com/theislab/scanpy.git
```

**Comment by grimwoo** [comment]
@flying-sheep Hi, I tried to install the new version of scanpy, but encountered errors.

first, I tried your code 
```
pip install git+https://github.com/theislab/scanpy.git 
```
I got ouput as:
```
Collecting git+https://github.com/theislab/scanpy.git
  Cloning https://github.com/theislab/scanpy.git to /tmp/pip-_z2v8och-build
fatal: Unable to find remote helper for 'https'
Command "git clone -q https://github.com/theislab/scanpy.git /tmp/pip-_z2v8och-build" failed with error code 128 in None
```

second, I tried
 ```
pip install git+git://github.com/theislab/scanpy.git 
```
I got ouput as:
```
Collecting git+git://github.com/theislab/scanpy.git
  Cloning git://github.com/theislab/scanpy.git to /tmp/pip-2jry40l_-build
```
and there was no more information and I have to stop it with "ctrl+C".

third, I tried to download the zip and `cd` to that directory and used 

```
python setup.py build
```

I got ouput as:

```
importlib_metadata.PackageNotFoundError: scanpy
```

after this, I tried 

```
pip install -e .
```

I got ouput as:

```
Command "python setup.py egg_info" failed with error code 1 in /public-supool/home/wuhaoda/Scanpy/Download/scanpy-master/
```

I searched the relative information in GitHub/Scanpy, but still have no solution for my situation.

the following was another failed code.

``` 
pip install https://github.com/theislab/scanpy.git
```

output:

```
Collecting https://github.com/theislab/scanpy.git
  Downloading https://github.com/theislab/scanpy.git
     \ 143kB 442kB/s
  Cannot unpack file /tmp/pip-chtzh_a9-unpack/scanpy.git (downloaded from /tmp/pip-xolhyav7-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-xolhyav7-build
```

and i also tried

```
git clone --recursive git://github.com/theislab/scanpy.git
```

output:

```
Cloning into 'scanpy'...
remote: Enumerating objects: 122, done.
remote: Counting objects: 100% (122/122), done.
remote: Compressing objects: 100% (109/109), done.
Receiving objects:   3% (577/14992), 156.00 KiB | 3.00 KiB/s
fatal: The remote end hung up unexpectedly MiB | 28.00 KiB/s
fatal: early EOF
fatal: index-pack failed
```

however, i can successfully install scanpy 1.4.4 with

```
pip install scanpy
```

**Comment by flying-sheep** [comment]
>     pip install git+git://github.com/theislab/scanpy.git 

should have worked, there seems to be a problem with your git installation or internet.

>     importlib_metadata.PackageNotFoundError: scanpy

That’s my mistake, seems like a broke installing from .zips (not that anyone tried so far, installing from git is more convenient)

>     pip install https://github.com/theislab/scanpy.git

This won’t work, `pip install http...` means “install me a `sdist` or `wheel` downloadable from that URL”, but there’s no sdist or wheel at that URL, but a git repository.

>     git clone --recursive git://github.com/theislab/scanpy.git

again, this should work, probably a problem with your internet or git installation.

**Comment by flying-sheep** [comment]
What you can do is

1. go into the folder from the extracted zip
2. `git init`
3. `git tag v1.4.5.dev0`
4. `pip install -e .`

**Comment by grimwoo** [comment]
@flying-sheep I got the similar result.

```python
>>> scanpy-master]$ ls
conftest.py  CONTRIBUTING.md  docs  LICENSE  MANIFEST.in  pyproject.toml  pytest.ini  README.rst  requirements.txt  scanpy  setup.py
>>> scanpy-master]$ git init
Reinitialized existing Git repository in /public-supool/home/wuhaoda/Scanpy/Download/scanpy-master/.git/
>>> scanpy-master]$ git tag v1.4.5.dev0
fatal: Failed to resolve 'HEAD' as a valid ref.
>>> scanpy-master]$ pip install -e .
Obtaining file:///public-supool/home/wuhaoda/Scanpy/Download/scanpy-master
    Complete output from command python setup.py egg_info:
Traceback (most recent call last):
      File "/public-supool/home/wuhaoda/Scanpy/Download/scanpy-master/scanpy/__init__.py", line 25, in <module>
        from setuptools_scm import get_version
    ModuleNotFoundError: No module named 'setuptools_scm'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/public-supool/home/wuhaoda/Scanpy/Download/scanpy-master/setup.py", line 11, in <module>
        from scanpy import __author__, __email__
      File "/public-supool/home/wuhaoda/Scanpy/Download/scanpy-master/scanpy/__init__.py", line 29, in <module>
        __version__ = version(__name__)
      File "/public-supool/home/wuhaoda/Scanpy/Download/scanpy-master/scanpy/_utils.py", line 29, in version
        return version(package)
      File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 438, in version
        return distribution(package).version
      File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 411, in distribution
        return Distribution.from_name(package)
      File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 184, in from_name
        raise PackageNotFoundError(name)
    importlib_metadata.PackageNotFoundError: scanpy

    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /public-supool/home/wuhaoda/Scanpy/Download/scanpy-master/
```

**Comment by flying-sheep** [comment]
```
ModuleNotFoundError: No module named 'setuptools_scm'
```

Aha! well, I’d like you to look out for obvious and fixable problems like this and fix them before you turn for help. I’m helping many people for free and a bit of thinking for oneself goes a long way.

**Comment by grimwoo** [comment]
@flying-sheep Thanks~~ I would try to google this problem right now.
