### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by wgmao** [scverse/scanpy#855]
When I tried to import scanpy into python 3.5.2, I got the following error message,

```
>>> import scanpy as sc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/scanpy/__init__.py", line 3, in <module>
    from .utils import check_versions, annotate_doc_types
  File "/usr/local/lib/python3.5/dist-packages/scanpy/utils.py", line 18, in <module>
    from ._settings import settings
  File "/usr/local/lib/python3.5/dist-packages/scanpy/_settings.py", line 351
    f'{k} = {v!r}'
                 ^
SyntaxError: invalid syntax
```
My OS platform is `Ubuntu 16.04` and I installed `scanpy` by `pip install scanpy`. How could I resolve this issue? Thanks.

**Comment by ivirshup** [comment]
Hi! In general, we support python 3.6+ (f-strings are just too nice to not have). Are you able to use a newer version of python instead?

**Comment by wgmao** [comment]
Thanks for the suggestion. I actually solved the problem by installing a local miniconda with newer version of Python 3. Thank you.

**Comment by ivirshup** [comment]
No problem!
