### ISSUE TITLE
Cannot do "pip3.6 install scanpy"

### ISSUE THREAD

**Issue by maximilianh** [scverse/scanpy#90]
Any ideas what's going on here? I can't do a "pip3.6 install scanpy" on our linux cluster:

<details>

```
Collecting scanpy
  Using cached scanpy-0.4.3.tar.gz
Requirement already up-to-date: anndata>=0.5 in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: matplotlib==2.0.0 in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: pandas>=0.21 in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: scipy in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: seaborn in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: psutil in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: h5py in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: xlrd in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: scikit-learn>=0.19.1 in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: statsmodels in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: networkx in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: natsort in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: joblib in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: profilehooks in /cluster/software/lib/python3.6/site-packages (from scanpy)
Requirement already up-to-date: cycler>=0.10 in /cluster/software/lib/python3.6/site-packages (from matplotlib==2.0.0->scanpy)
Collecting python-dateutil (from matplotlib==2.0.0->scanpy)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting pytz (from matplotlib==2.0.0->scanpy)
  Using cached pytz-2018.3-py2.py3-none-any.whl
Requirement already up-to-date: six>=1.10 in /cluster/software/lib/python3.6/site-packages (from matplotlib==2.0.0->scanpy)
Requirement already up-to-date: numpy>=1.7.1 in /cluster/software/lib/python3.6/site-packages (from matplotlib==2.0.0->scanpy)
Requirement already up-to-date: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /cluster/software/lib/python3.6/site-packages (from matplotlib==2.0.0->scan
Requirement already up-to-date: patsy in /cluster/software/lib/python3.6/site-packages (from statsmodels->scanpy)
Requirement already up-to-date: decorator>=4.1.0 in /cluster/software/lib/python3.6/site-packages (from networkx->scanpy)
Installing collected packages: scanpy, python-dateutil, pytz
  Running setup.py install for scanpy: started
    Running setup.py install for scanpy: finished with status 'error'
    Complete output from command /cluster/software/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/scratch/tmp/pip-build-g14yf1xi/scanpy/setup.py';
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/scanpy
    copying scanpy/settings.py -> build/lib.linux-x86_64-3.6/scanpy
    copying scanpy/_version.py -> build/lib.linux-x86_64-3.6/scanpy
    copying scanpy/__init__.py -> build/lib.linux-x86_64-3.6/scanpy
    copying scanpy/__main__.py -> build/lib.linux-x86_64-3.6/scanpy
    copying scanpy/readwrite.py -> build/lib.linux-x86_64-3.6/scanpy
    copying scanpy/utils.py -> build/lib.linux-x86_64-3.6/scanpy
    copying scanpy/exporting.py -> build/lib.linux-x86_64-3.6/scanpy
    copying scanpy/logging.py -> build/lib.linux-x86_64-3.6/scanpy
    creating build/lib.linux-x86_64-3.6/scanpy/plotting                                                                                                            copying scanpy/plotting/top_genes_visual.py -> build/lib.linux-x86_64-3.6/scanpy/plotting                                                                      copying scanpy/plotting/rcmod.py -> build/lib.linux-x86_64-3.6/scanpy/plotting
    copying scanpy/plotting/ann_data.py -> build/lib.linux-x86_64-3.6/scanpy/plotting
    copying scanpy/plotting/preprocessing.py -> build/lib.linux-x86_64-3.6/scanpy/plotting
    copying scanpy/plotting/__init__.py -> build/lib.linux-x86_64-3.6/scanpy/plotting
    copying scanpy/plotting/palettes.py -> build/lib.linux-x86_64-3.6/scanpy/plotting
    copying scanpy/plotting/tools.py -> build/lib.linux-x86_64-3.6/scanpy/plotting
    copying scanpy/plotting/utils.py -> build/lib.linux-x86_64-3.6/scanpy/plotting
    creating build/lib.linux-x86_64-3.6/scanpy/data_structs
    copying scanpy/data_structs/data_graph.py -> build/lib.linux-x86_64-3.6/scanpy/data_structs
    copying scanpy/data_structs/__init__.py -> build/lib.linux-x86_64-3.6/scanpy/data_structs
    creating build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/score_gene_lists.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/diffmap.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/_tsne_fix.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/sim.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/draw_graph.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/pca.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/__init__.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/rank_genes_groups.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/tsne.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/dpt.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/top_genes.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/aga.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    copying scanpy/tools/louvain.py -> build/lib.linux-x86_64-3.6/scanpy/tools
    writing scanpy.egg-info/PKG-INFO
    writing entry points to scanpy.egg-info/entry_points.txt
    writing top-level names to scanpy.egg-info/top_level.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'scanpy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'scanpy.egg-info/SOURCES.txt'
```
```pytb
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/scratch/tmp/pip-build-g14yf1xi/scanpy/setup.py", line 83, in <module>
        'Topic :: Scientific/Engineering :: Visualization',
      File "/cluster/software/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/cluster/software/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/cluster/software/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/cluster/software/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/cluster/software/lib/python3.6/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/cluster/software/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/cluster/software/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/cluster/software/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/cluster/software/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/cluster/software/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/scratch/tmp/pip-build-g14yf1xi/scanpy/versioneer.py", line 1555, in run
        _build_py.run(self)
      File "/cluster/software/lib/python3.6/site-packages/setuptools/command/build_py.py", line 52, in run
        self.build_package_data()
      File "/cluster/software/lib/python3.6/site-packages/setuptools/command/build_py.py", line 107, in build_package_data
        for package, src_dir, build_dir, filenames in self.data_files:
      File "/cluster/software/lib/python3.6/site-packages/setuptools/command/build_py.py", line 65, in __getattr__
        self.data_files = self._get_data_files()
      File "/cluster/software/lib/python3.6/site-packages/setuptools/command/build_py.py", line 79, in _get_data_files
        return list(map(self._get_pkg_data_files, self.packages or ()))
      File "/cluster/software/lib/python3.6/site-packages/setuptools/command/build_py.py", line 91, in _get_pkg_data_files
        for file in self.find_data_files(package, src_dir)
      File "/cluster/software/lib/python3.6/site-packages/setuptools/command/build_py.py", line 98, in find_data_files
        + self.package_data.get(package, []))
    TypeError: must be str, not list
```

</details>

I have never had this error message before and Google can't find anything. 

Debugging this a bit, it happens because in this line in build_py.py:

```py
        globs = (self.package_data.get('', [])
                 + self.package_data.get(package, []))
```

package is "scanpy" and the first part before the + is `"*.txt"` and the second part after the + is `[]`

This is Python 3.6.0a1 and pip 9.0.1 on Centos 6.8

**Comment by falexwolf** [comment]
Grrr, this seems to be something in setuptools... @flying-sheep are we calling something  in setup.py that might leed to these strange effects?

Please have a bit patience, we will try to reproduce this...

**Comment by flying-sheep** [comment]
Thank you @maximilianh for debugging this and telling us the actual values here! That’s super helpful, and would help maintainers extremely if everybody did it. But I think it’s relatively advanced to do it, so I understand when people don’t.

OK, what I can glean from the traceback:

1. setup.py is invoked
2. `self.run_command('build')` might mean that `setup.py build` is invoked
3. …/scanpy/versioneer.py → `_build_py.run(self)` so at some point some command defined by the versioneer is used
4. as @maximilianh said, the end is a line in `build_py.py`…

…which was [replaced two years ago](https://github.com/pypa/setuptools/commit/4f6fc8537842c14b03c4a1ffd25b88f2f4c276c6), in version 25.1.2. (Current version is 38.5.1)

Could you please try updating your packages to see if there’s still an issue?

**Comment by maximilianh** [comment]
Oh! I did upgrade pip and all the packages needed by scanpy, but didn't have the idea of doing:

    pip3 install --upgrade setuptools

This fixed it! Many thanks!

**Comment by maximilianh** [comment]
Again, many thanks for your super quick help!

**Comment by flying-sheep** [comment]
NP :smile:
